INSERT INTO `authors` VALUES('0','Carol Ryrie Brink')
INSERT INTO `authors` VALUES('1','Judith Rossner')
INSERT INTO `authors` VALUES('2','TAMI HOAG')
INSERT INTO `authors` VALUES('3','Venise T. Berry')
INSERT INTO `authors` VALUES('4','Meg Cabot')
INSERT INTO `authors` VALUES('5','Hazel Harrison')
INSERT INTO `authors` VALUES('6','Nevada Barr')
INSERT INTO `authors` VALUES('7','Luis Sep�?ºlveda')
INSERT INTO `authors` VALUES('8','William Eisner')
INSERT INTO `authors` VALUES('9','Mark Helprin')
INSERT INTO `authors` VALUES('10','Candice F. Ransom')
INSERT INTO `authors` VALUES('11','Sue Townsend')
INSERT INTO `authors` VALUES('12','Chuck Hill')
INSERT INTO `authors` VALUES('13','Linda Lay Shuler')
INSERT INTO `authors` VALUES('14','Ian McEwan')
INSERT INTO `authors` VALUES('15','Patricia Gaffney')
INSERT INTO `authors` VALUES('16','Pearl Abraham')
INSERT INTO `authors` VALUES('17','Anne Frasier')
INSERT INTO `authors` VALUES('18','Alisa Kwitney')
INSERT INTO `authors` VALUES('19','Isabel-Clara Simó')
INSERT INTO `authors` VALUES('20','Paul Phifer')
INSERT INTO `authors` VALUES('21','Orson Scott Card')
INSERT INTO `authors` VALUES('22','JOHN GRISHAM')
INSERT INTO `authors` VALUES('23','Lisa Jackson')
INSERT INTO `authors` VALUES('24','Erma Bombeck')
INSERT INTO `authors` VALUES('25','Carole Nelson Douglas')
INSERT INTO `authors` VALUES('26','A. C. Gordon')
INSERT INTO `authors` VALUES('27','Martin Schenk')
INSERT INTO `authors` VALUES('28','Tom Wolfe')
INSERT INTO `authors` VALUES('29','Ann Patchett')
INSERT INTO `authors` VALUES('30','Dick Francis')
INSERT INTO `authors` VALUES('31','Lorna Landvik')
INSERT INTO `authors` VALUES('32','Willa Cather')
INSERT INTO `authors` VALUES('33','The Onion')
INSERT INTO `authors` VALUES('34','Luanne Rice')
INSERT INTO `authors` VALUES('35','Christa Wolf')
INSERT INTO `authors` VALUES('36','William J. Kennedy')
INSERT INTO `authors` VALUES('37','LEE SMITH')
INSERT INTO `authors` VALUES('38','Charles Bukowski')
INSERT INTO `authors` VALUES('39','L.M. MONTGOMERY')
INSERT INTO `authors` VALUES('40','Sarah Ban Breathnach')
INSERT INTO `authors` VALUES('41','Màrius Serra')
INSERT INTO `authors` VALUES('42','Carl Sagan')
INSERT INTO `authors` VALUES('43','Cyrano de Bergerac')
INSERT INTO `authors` VALUES('44','Gina Bari Kolata')
INSERT INTO `authors` VALUES('45','John Darnton')
INSERT INTO `authors` VALUES('46','Michael Moore')
INSERT INTO `authors` VALUES('47','Gwyn Hyman Rubio')
INSERT INTO `authors` VALUES('48','Tim Farrington')
INSERT INTO `authors` VALUES('49','Roland Warren')
INSERT INTO `authors` VALUES('50','Sylvia Plath')
INSERT INTO `authors` VALUES('51','J. R. Parrish')
INSERT INTO `authors` VALUES('52','Kathleen Duey')
INSERT INTO `authors` VALUES('53','KRISTIN HANNAH')
INSERT INTO `authors` VALUES('54','Jean Giono')
INSERT INTO `authors` VALUES('55','Anne Rice')
INSERT INTO `authors` VALUES('56','Wayne W. Dyer')
INSERT INTO `authors` VALUES('57','DAVID SCHICKLER')
INSERT INTO `authors` VALUES('58','Michael Hudson')
INSERT INTO `authors` VALUES('59','Anthony Trollope')
INSERT INTO `authors` VALUES('60','Tawni O\'Dell')
INSERT INTO `authors` VALUES('61','Rich Shapero')
INSERT INTO `authors` VALUES('62','Sally Mandel')
INSERT INTO `authors` VALUES('63','Samuel Richardson')
INSERT INTO `authors` VALUES('64','Ofèlia Dracs')
INSERT INTO `authors` VALUES('65','Barry Lopez')
INSERT INTO `authors` VALUES('66','Karen Stolz')
INSERT INTO `authors` VALUES('67','MAYA ANGELOU')
INSERT INTO `authors` VALUES('68','Scott Turow')
INSERT INTO `authors` VALUES('69','Nick Page')
INSERT INTO `authors` VALUES('70','Nancy Garden')
INSERT INTO `authors` VALUES('71','Julia Oliver')
INSERT INTO `authors` VALUES('72','Bobbie Kalman')
INSERT INTO `authors` VALUES('73','Jacquelyn Mitchard')
INSERT INTO `authors` VALUES('74','Charles Dickens')
INSERT INTO `authors` VALUES('75','Gary Paulsen')
INSERT INTO `authors` VALUES('76','Stanley Morison')
INSERT INTO `authors` VALUES('77','Ariella Papa')
INSERT INTO `authors` VALUES('78','Stephen King')
INSERT INTO `authors` VALUES('79','Bernard Werber')
INSERT INTO `authors` VALUES('80','Robert Cowley')
INSERT INTO `authors` VALUES('81','Sandra Brown')
INSERT INTO `authors` VALUES('82','Walter Wick')
INSERT INTO `authors` VALUES('83','R. J. Kaiser')
INSERT INTO `authors` VALUES('84','Lawrence J Crabb')
INSERT INTO `authors` VALUES('85','Dave Barry')
INSERT INTO `authors` VALUES('86','RAY BRADBURY')
INSERT INTO `authors` VALUES('87','Jennifer Weiner')
INSERT INTO `authors` VALUES('88','Richard A. Lupoff')
INSERT INTO `authors` VALUES('89','Armistead Maupin')
INSERT INTO `authors` VALUES('90','Charles R. Swindoll')
INSERT INTO `authors` VALUES('91','Malcolm Goodway')
INSERT INTO `authors` VALUES('92','Angela Elwell Hunt')
INSERT INTO `authors` VALUES('93','EDWARD RUTHERFURD')
INSERT INTO `authors` VALUES('94','Blanche Fisher Wright')
INSERT INTO `authors` VALUES('95','Edith Wharton')
INSERT INTO `authors` VALUES('96','Jack Kerouac')
INSERT INTO `authors` VALUES('97','Michael Slade')
INSERT INTO `authors` VALUES('98','Clifford Stoll')
INSERT INTO `authors` VALUES('99','LAURA HILLENBRAND')
INSERT INTO `authors` VALUES('100','Carl Hausman')
INSERT INTO `authors` VALUES('101','Sherry Garland')
INSERT INTO `authors` VALUES('102','J.D. Robb')
INSERT INTO `authors` VALUES('103','Paolo Coelho')
INSERT INTO `authors` VALUES('104','Patricia Cornwell')
INSERT INTO `authors` VALUES('105','DEAN KOONTZ')
INSERT INTO `authors` VALUES('106','Enid Blyton')
INSERT INTO `authors` VALUES('107','Milan Kundera')
INSERT INTO `authors` VALUES('108','Tony Parsons')
INSERT INTO `authors` VALUES('109','John A. Keel')
INSERT INTO `authors` VALUES('110','Ferran Torrent')
INSERT INTO `authors` VALUES('111','Pergaud')
INSERT INTO `authors` VALUES('112','John G. Neihardt')
INSERT INTO `authors` VALUES('113','Isabelle Holland')
INSERT INTO `authors` VALUES('114','John Galsworthy')
INSERT INTO `authors` VALUES('115','Susan Grant')
INSERT INTO `authors` VALUES('116','Mary Wollstonecraft Shelley')
INSERT INTO `authors` VALUES('117','Nick Hornby')
INSERT INTO `authors` VALUES('118','Tracy Chevalier')
INSERT INTO `authors` VALUES('119','Frank M. Robinson')
INSERT INTO `authors` VALUES('120','Frank Waters')
INSERT INTO `authors` VALUES('121','Judith Kelman')
INSERT INTO `authors` VALUES('122','Leon Hale')
INSERT INTO `authors` VALUES('123','Maeve Binchy')
INSERT INTO `authors` VALUES('124','H. Norman Wright')
INSERT INTO `authors` VALUES('125','Charles L. Squire')
INSERT INTO `authors` VALUES('126','Marc Levy')
INSERT INTO `authors` VALUES('127','Víctor Mora')
INSERT INTO `authors` VALUES('128','Ray Bradbury')
INSERT INTO `authors` VALUES('129','Mark Cohen')
INSERT INTO `authors` VALUES('130','Aleksandr Zinoviev')
INSERT INTO `authors` VALUES('131','A.C. Crispin')
INSERT INTO `authors` VALUES('132','Phyllis Reynolds Naylor')
INSERT INTO `authors` VALUES('133','Rene Barjavel')
INSERT INTO `authors` VALUES('134','JODI COMPTON')
INSERT INTO `authors` VALUES('135','Rita Chapman Works')
INSERT INTO `authors` VALUES('136','Beverly Hastings')
INSERT INTO `authors` VALUES('137','David Lewis')
INSERT INTO `authors` VALUES('138','LORNA LANDVIK')
INSERT INTO `authors` VALUES('139','Wally Lamb')
INSERT INTO `authors` VALUES('140','Raymond Radiguet')
INSERT INTO `authors` VALUES('141','Norman Bridwell')
INSERT INTO `authors` VALUES('142','Anita Shreve')
INSERT INTO `authors` VALUES('143','Maria Jaén')
INSERT INTO `authors` VALUES('144','Carrie Bebris')
INSERT INTO `authors` VALUES('145','P. D. James')
INSERT INTO `authors` VALUES('146','Moon Unit Zappa')
INSERT INTO `authors` VALUES('147','Alain-Fournier')
INSERT INTO `authors` VALUES('148','Sara Paretsky')
INSERT INTO `authors` VALUES('149','Stephen McCauley')
INSERT INTO `authors` VALUES('150','Anita Diamant')
INSERT INTO `authors` VALUES('151','Daphne Du Maurier')
INSERT INTO `authors` VALUES('152','Max Allan Collins')
INSERT INTO `authors` VALUES('153','Anne McCaffrey')
INSERT INTO `authors` VALUES('154','Rachel Harris')
INSERT INTO `authors` VALUES('155','Andrea Kane')
INSERT INTO `authors` VALUES('156','Bradley Warshauer')
INSERT INTO `authors` VALUES('157','Stefanie Scott')
INSERT INTO `authors` VALUES('158','Melisa Michaels')
INSERT INTO `authors` VALUES('159','Louisa May Alcott')
INSERT INTO `authors` VALUES('160','A. S. Byatt')
INSERT INTO `authors` VALUES('161','David Iglehart')
INSERT INTO `authors` VALUES('162','Louis L\'Amour')
INSERT INTO `authors` VALUES('163','Joyce Reardon')
INSERT INTO `authors` VALUES('164','Richard Paul Evans')
INSERT INTO `authors` VALUES('165','Anna Sewell')
INSERT INTO `authors` VALUES('166','Georgette Heyer')
INSERT INTO `authors` VALUES('167','Billie Livingston')
INSERT INTO `authors` VALUES('168','Paul Hattaway')
INSERT INTO `authors` VALUES('169','Michael Lewis')
INSERT INTO `authors` VALUES('170','Donna K Grosvenor')
INSERT INTO `authors` VALUES('171','Lisa Scottoline')
INSERT INTO `authors` VALUES('172','Gregory Maguire')
INSERT INTO `authors` VALUES('173','Fannie Flagg')
INSERT INTO `authors` VALUES('174','Don Miguel Ruiz')
INSERT INTO `authors` VALUES('175','Jonathan Franzen')
INSERT INTO `authors` VALUES('176','Craig Boldman')
INSERT INTO `authors` VALUES('177','Yann Martel')
INSERT INTO `authors` VALUES('178','Tamora Pierce')
INSERT INTO `authors` VALUES('179','Norton Juster')
INSERT INTO `authors` VALUES('180','John T. Lescroart')
INSERT INTO `authors` VALUES('181','Toni Morrison')
INSERT INTO `authors` VALUES('182','Dog Mary Crow')
INSERT INTO `authors` VALUES('183','Arthur William Upfield')
INSERT INTO `authors` VALUES('184','Andrei Codrescu')
INSERT INTO `authors` VALUES('185','Christoph Hein')
INSERT INTO `authors` VALUES('186','Barbara Metzger')
INSERT INTO `authors` VALUES('187','Robert B. Parker')
INSERT INTO `authors` VALUES('188','Luis Racionero')
INSERT INTO `authors` VALUES('189','Ted Dekker')
INSERT INTO `authors` VALUES('190','Anne Perry')
INSERT INTO `authors` VALUES('191','David Steinman')
INSERT INTO `authors` VALUES('192','Celia Brooks Brown')
INSERT INTO `authors` VALUES('193','Jacob Weisberg')
INSERT INTO `authors` VALUES('194','Benjamin Hoff')
INSERT INTO `authors` VALUES('195','Bob Shacochis')
INSERT INTO `authors` VALUES('196','Michael Jan Friedman')
INSERT INTO `authors` VALUES('197','ANN BRASHARES')
INSERT INTO `authors` VALUES('198','Charles Sullivan')
INSERT INTO `authors` VALUES('199','O. Carol Simonton Md')
INSERT INTO `authors` VALUES('200','Sheila Heti')
INSERT INTO `authors` VALUES('201','Martin Buber')
INSERT INTO `authors` VALUES('202','Bill Bradley')
INSERT INTO `authors` VALUES('203','David Cordingly')
INSERT INTO `authors` VALUES('204','ROALD DAHL')
INSERT INTO `authors` VALUES('205','Barbara Delinsky')
INSERT INTO `authors` VALUES('206','Valerie Block')
INSERT INTO `authors` VALUES('207','Elizabeth Strout')
INSERT INTO `authors` VALUES('208','J.R.R. TOLKIEN')
INSERT INTO `authors` VALUES('209','Dawn Chipman')
INSERT INTO `authors` VALUES('210','William Shakespeare')
INSERT INTO `authors` VALUES('211','LOIS LOWRY')
INSERT INTO `authors` VALUES('212','Thomas Harris')
INSERT INTO `authors` VALUES('213','Iris Johansen')
INSERT INTO `authors` VALUES('214','Jesse S. Ostrow')
INSERT INTO `authors` VALUES('215','Julia Spencer-Fleming')
INSERT INTO `authors` VALUES('216','Sara Orwig')
INSERT INTO `authors` VALUES('217','Ralph Ellison')
INSERT INTO `authors` VALUES('218','Eileen Goudge')
INSERT INTO `authors` VALUES('219','Dean Koontz')
INSERT INTO `authors` VALUES('220','Henry Miller')
INSERT INTO `authors` VALUES('221','Frances Hodgson  Burnett')
INSERT INTO `authors` VALUES('222','Steve Thayer')
INSERT INTO `authors` VALUES('223','John Berendt')
INSERT INTO `authors` VALUES('224','Tanith Lee')
INSERT INTO `authors` VALUES('225','Lauren Haney')
INSERT INTO `authors` VALUES('226','Marc Reisner')
INSERT INTO `authors` VALUES('227','DIANE MOTT DAVIDSON')
INSERT INTO `authors` VALUES('228','Rex Stout')
INSERT INTO `authors` VALUES('229','Homer Hickam')
INSERT INTO `authors` VALUES('230','Valerie Martin')
INSERT INTO `authors` VALUES('231','Sir Arthur Conan Doyle')
INSERT INTO `authors` VALUES('232','Dorothy Allison')
INSERT INTO `authors` VALUES('233','Gabriel Garcia Marquez')
INSERT INTO `authors` VALUES('234','David Baldacci')
INSERT INTO `authors` VALUES('235','Catherine Coulter')
INSERT INTO `authors` VALUES('236','Spencer Johnson')
INSERT INTO `authors` VALUES('237','Manda Scott')
INSERT INTO `authors` VALUES('238','Carolyn See')
INSERT INTO `authors` VALUES('239','Ernest Hemingway')
INSERT INTO `authors` VALUES('240','Nicholas Evans')
INSERT INTO `authors` VALUES('241','Carlo D\'Este')
INSERT INTO `authors` VALUES('242','Jane Austen')
INSERT INTO `authors` VALUES('243','James Patterson')
INSERT INTO `authors` VALUES('244','Dean R. Koontz')
INSERT INTO `authors` VALUES('245','Paula Danziger')
INSERT INTO `authors` VALUES('246','James Burke')
INSERT INTO `authors` VALUES('247','Irving. Adler')
INSERT INTO `authors` VALUES('248','Peter Straub')
INSERT INTO `authors` VALUES('249','Matthew Thomas')
INSERT INTO `authors` VALUES('250','Ann Beattie')
INSERT INTO `authors` VALUES('251','Harry M. Walker')
INSERT INTO `authors` VALUES('252','Roberto Juarroz')
INSERT INTO `authors` VALUES('253','Patricia Highsmith')
INSERT INTO `authors` VALUES('254','AGATHA CHRISTIE')
INSERT INTO `authors` VALUES('255','Paul Theroux')
INSERT INTO `authors` VALUES('256','John. Blofeld')
INSERT INTO `authors` VALUES('257','RICHARD NORTH PATTERSON')
INSERT INTO `authors` VALUES('258','Sebastian Junger')
INSERT INTO `authors` VALUES('259','Richard Brassey')
INSERT INTO `authors` VALUES('260','IRIS JOHANSEN')
INSERT INTO `authors` VALUES('261','JUDY BLUNT')
INSERT INTO `authors` VALUES('262','Philip Ardagh')
INSERT INTO `authors` VALUES('263','Bram Stoker')
INSERT INTO `authors` VALUES('264','Gordon Jarvie')
INSERT INTO `authors` VALUES('265','Stephanie Maze')
INSERT INTO `authors` VALUES('266','Leo Tolstoy')
INSERT INTO `authors` VALUES('267','Sheri S. Tepper')
INSERT INTO `authors` VALUES('268','Judy Hamilton')
INSERT INTO `authors` VALUES('269','Paul Jennings')
INSERT INTO `authors` VALUES('270','FRANCES KUFFEL')
INSERT INTO `authors` VALUES('271','E.H. Shepard')
INSERT INTO `authors` VALUES('272','Paul Monette')
INSERT INTO `authors` VALUES('273','Richard Bruce Wright')
INSERT INTO `authors` VALUES('274','Robert Hendrickson')
INSERT INTO `authors` VALUES('275','Eleanor Cooney')
INSERT INTO `authors` VALUES('276','David G. Hartwell')
INSERT INTO `authors` VALUES('277','William Trevor')
INSERT INTO `authors` VALUES('278','Roy')
INSERT INTO `authors` VALUES('279','Isabel Wolff')
INSERT INTO `authors` VALUES('280','Jaume Capó')
INSERT INTO `authors` VALUES('281','Kenneth Grahame')
INSERT INTO `authors` VALUES('282','Adam Davies')
INSERT INTO `authors` VALUES('283','Barbara Ehrenreich')
INSERT INTO `authors` VALUES('284','Richard North Patterson')
INSERT INTO `authors` VALUES('285','A.S. BYATT')
INSERT INTO `authors` VALUES('286','AD HUDLER')
INSERT INTO `authors` VALUES('287','Alice McDermott')
INSERT INTO `authors` VALUES('288','Carol J. Farley')
INSERT INTO `authors` VALUES('289','Dinah L. Moche')
INSERT INTO `authors` VALUES('290','P Coelho')
INSERT INTO `authors` VALUES('291','Lauren Maddison')
INSERT INTO `authors` VALUES('292','John Bellairs')
INSERT INTO `authors` VALUES('293','Tom Clancy')
INSERT INTO `authors` VALUES('294','EMILY BRONTE')
INSERT INTO `authors` VALUES('295','Mark Bowden')
INSERT INTO `authors` VALUES('296','Frank E. Peretti')
INSERT INTO `authors` VALUES('297','Helen Fielding')
INSERT INTO `authors` VALUES('298','Madelyn Arnold')
INSERT INTO `authors` VALUES('299','E. LYNN HARRIS')
INSERT INTO `authors` VALUES('300','H. Jackson Brown')
INSERT INTO `authors` VALUES('301','Dan Quayle')
INSERT INTO `authors` VALUES('302','Tilden H. Edwards')
INSERT INTO `authors` VALUES('303','Fern Michaels')
INSERT INTO `authors` VALUES('304','John Mortimer')
INSERT INTO `authors` VALUES('305','Randy Alcorn')
INSERT INTO `authors` VALUES('306','Bob Sjogren')
INSERT INTO `authors` VALUES('307','TIM GAUTREAUX')
INSERT INTO `authors` VALUES('308','Wallace Stegner')
INSERT INTO `authors` VALUES('309','Nancy Cobb')
INSERT INTO `authors` VALUES('310','DAVID FRUM')
INSERT INTO `authors` VALUES('311','C. Baudelaire')
INSERT INTO `authors` VALUES('312','Rebecca Winters')
INSERT INTO `authors` VALUES('313','Christine Obbo')
INSERT INTO `authors` VALUES('314','Shana Corey')
INSERT INTO `authors` VALUES('315','Shirlee Busbee')
INSERT INTO `authors` VALUES('316','Elizabeth Peters')
INSERT INTO `authors` VALUES('317','Dan Brown')
INSERT INTO `authors` VALUES('318','Faye Kellerman')
INSERT INTO `authors` VALUES('319','Shel Silverstein')
INSERT INTO `authors` VALUES('320','Lynn Coady')
INSERT INTO `authors` VALUES('321','Brian Kaufman')
INSERT INTO `authors` VALUES('322','Thomas Hardy')
INSERT INTO `authors` VALUES('323','Jack Higgins')
INSERT INTO `authors` VALUES('324','Pam Conrad')
INSERT INTO `authors` VALUES('325','Wilbur Smith')
INSERT INTO `authors` VALUES('326','Jo Dereske')
INSERT INTO `authors` VALUES('327','Mary Lawson')
INSERT INTO `authors` VALUES('328','Andrew Clements')
INSERT INTO `authors` VALUES('329','Erich Maria Remarque')
INSERT INTO `authors` VALUES('330','Alan Spence')
INSERT INTO `authors` VALUES('331','Julie Campbell')
INSERT INTO `authors` VALUES('332','Anne Rivers Siddons')
INSERT INTO `authors` VALUES('333','Claude Lanzmann')
INSERT INTO `authors` VALUES('334','Emma Lathen')
INSERT INTO `authors` VALUES('335','Judith Guest')
INSERT INTO `authors` VALUES('336','Jostein Gaarder')
INSERT INTO `authors` VALUES('337','Langston Hughes')
INSERT INTO `authors` VALUES('338','MICHAEL ONDAATJE')
INSERT INTO `authors` VALUES('339','Arabella Weir')
INSERT INTO `authors` VALUES('340','Anne Dingus')
INSERT INTO `authors` VALUES('341','TOM ROBBINS')
INSERT INTO `authors` VALUES('342','Dolores Krieger')
INSERT INTO `authors` VALUES('343','Joseph Conrad')
INSERT INTO `authors` VALUES('344','Paul Woodruff')
INSERT INTO `authors` VALUES('345','Ursula Hegi')
INSERT INTO `authors` VALUES('346','Frederick J. Moody')
INSERT INTO `authors` VALUES('347','JACQUELINE WOODSON')
INSERT INTO `authors` VALUES('348','Jean Marzollo')
INSERT INTO `authors` VALUES('349','DIANA GABALDON')
INSERT INTO `authors` VALUES('350','Terry Pratchett')
INSERT INTO `authors` VALUES('351','Barbara Michaels')
INSERT INTO `authors` VALUES('352','Emily Bronte')
INSERT INTO `authors` VALUES('353','Travis Thrasher')
INSERT INTO `authors` VALUES('354','Bernard Cornwell')
INSERT INTO `authors` VALUES('355','Tanuja Desai Hidier')
INSERT INTO `authors` VALUES('356','Alexandra David-N�?©el')
INSERT INTO `authors` VALUES('357','Jody Seay')
INSERT INTO `authors` VALUES('358','Todd Herzog')
INSERT INTO `authors` VALUES('359','Trudy Suggs')
INSERT INTO `authors` VALUES('360','Emile Zola')
INSERT INTO `authors` VALUES('361','Lewis Carroll')
INSERT INTO `authors` VALUES('362','Tobias Wolff')
INSERT INTO `authors` VALUES('363','Mordecai Richler')
INSERT INTO `authors` VALUES('364','Simon Schama')
INSERT INTO `authors` VALUES('365','Chris Anne Wolfe')
INSERT INTO `authors` VALUES('366','Sandra Levy Ceren')
INSERT INTO `authors` VALUES('367','Michael Blake')
INSERT INTO `authors` VALUES('368','Margaret Atwood')
INSERT INTO `authors` VALUES('369','Mercedes Lackey')
INSERT INTO `authors` VALUES('370','CHARLES FRAZIER')
INSERT INTO `authors` VALUES('371','David Crombie')
INSERT INTO `authors` VALUES('372','Susan Conant')
INSERT INTO `authors` VALUES('373','Richard Bach')
INSERT INTO `authors` VALUES('374','Kevin Sullivan')
INSERT INTO `authors` VALUES('375','Ted L. Nancy')
INSERT INTO `authors` VALUES('376','Henry James')
INSERT INTO `authors` VALUES('377','Pat Hutchins')
INSERT INTO `authors` VALUES('378','Carl Hiaasen')
INSERT INTO `authors` VALUES('379','Charles Noland')
INSERT INTO `authors` VALUES('380','Ivan Doig')
INSERT INTO `authors` VALUES('381','JULIA GLASS')
INSERT INTO `authors` VALUES('382','Alain de Botton')
INSERT INTO `authors` VALUES('383','William Carlos Williams')
INSERT INTO `authors` VALUES('384','Jeffrey Eugenides')
INSERT INTO `authors` VALUES('385','Richard Webster')
INSERT INTO `authors` VALUES('386','John Sandford')
INSERT INTO `authors` VALUES('387','Jane Smiley')
INSERT INTO `authors` VALUES('388','Spalding Gray')
INSERT INTO `authors` VALUES('389','A. Manette Ansay')
INSERT INTO `authors` VALUES('390','Dominick Dunne')
INSERT INTO `authors` VALUES('391','Robert Lacey')
INSERT INTO `authors` VALUES('392','Mary Jane Clark')
INSERT INTO `authors` VALUES('393','James McCourt')
INSERT INTO `authors` VALUES('394','Nathaniel Hawthorne')
INSERT INTO `authors` VALUES('395','DANA REEVE')
INSERT INTO `authors` VALUES('396','Russell Banks')
INSERT INTO `authors` VALUES('397','John Steinbeck')
INSERT INTO `authors` VALUES('398','Eileen Yin-Fei Lo')
INSERT INTO `authors` VALUES('399','Candace Bushnell')
INSERT INTO `authors` VALUES('400','Mitch Albom')
INSERT INTO `authors` VALUES('401','Shannon Olson')
INSERT INTO `authors` VALUES('402','William Sleator')
INSERT INTO `authors` VALUES('403','Bobbie Ann Mason')
INSERT INTO `authors` VALUES('404','Boris Vian')
INSERT INTO `authors` VALUES('405','Mike Gayle')
INSERT INTO `authors` VALUES('406','Marilyn French')
INSERT INTO `authors` VALUES('407','Andy Sloss')
INSERT INTO `authors` VALUES('408','LOUIS DE BERNIERES')
INSERT INTO `authors` VALUES('409','Helen Brooks')
INSERT INTO `authors` VALUES('410','Martha Grimes')
INSERT INTO `authors` VALUES('411','Lorraine Anderson')
INSERT INTO `authors` VALUES('412','Ellen Rimbauer')
INSERT INTO `authors` VALUES('413','Joanna Trollope')
INSERT INTO `authors` VALUES('414','Lilian Jackson Braun')
INSERT INTO `authors` VALUES('415','Helene Siegel')
INSERT INTO `authors` VALUES('416','Piers Anthony')
INSERT INTO `authors` VALUES('417','Stephen J. Weininger')
INSERT INTO `authors` VALUES('418','Mark Salzman')
INSERT INTO `authors` VALUES('419','Josephine Carlton')
INSERT INTO `authors` VALUES('420','Malachy McCourt')
INSERT INTO `authors` VALUES('421','Julie Morgenstern')
INSERT INTO `authors` VALUES('422','Linda Howard')
INSERT INTO `authors` VALUES('423','Jhumpa Lahiri')
INSERT INTO `authors` VALUES('424','Lauren Sanders')
INSERT INTO `authors` VALUES('425','Elizabeth Laird')
INSERT INTO `authors` VALUES('426','Sharyn McCrumb')
INSERT INTO `authors` VALUES('427','Ruth Rendell')
INSERT INTO `authors` VALUES('428','Francis Wheen')
INSERT INTO `authors` VALUES('429','Mike Thaler')
INSERT INTO `authors` VALUES('430','Alice Walker')
INSERT INTO `authors` VALUES('431','Joanne Harris')
INSERT INTO `authors` VALUES('432','Karen X. Tulchinsky')
INSERT INTO `authors` VALUES('433','Warren  Bennis')
INSERT INTO `authors` VALUES('434','Ken Follett')
INSERT INTO `authors` VALUES('435','Suzanne Brockmann')
INSERT INTO `authors` VALUES('436','MICHAEL CRICHTON')
INSERT INTO `authors` VALUES('437','Douglas Adams')
INSERT INTO `authors` VALUES('438','Al Franken')
INSERT INTO `authors` VALUES('439','Tim Dorsey')
INSERT INTO `authors` VALUES('440','Karen Robards')
INSERT INTO `authors` VALUES('441','Karen Armstrong')
INSERT INTO `authors` VALUES('442','Ted Hughes')
INSERT INTO `authors` VALUES('443','Robert A Johnson')
INSERT INTO `authors` VALUES('444','HarperReference')
INSERT INTO `authors` VALUES('445','Gail Carson Levine')
INSERT INTO `authors` VALUES('446','Franklin W. Dixon')
INSERT INTO `authors` VALUES('447','Kay Hooper')
INSERT INTO `authors` VALUES('448','Mary Higgins Clark')
INSERT INTO `authors` VALUES('449','Joseph Girzone')
INSERT INTO `authors` VALUES('450','SHARYN MCCRUMB')
INSERT INTO `authors` VALUES('451','Deepak Chopra')
INSERT INTO `authors` VALUES('452','LOIS DUNCAN')
INSERT INTO `authors` VALUES('453','Mary Brave Bird')
INSERT INTO `authors` VALUES('454','Ann Rule')
INSERT INTO `authors` VALUES('455','Stephen Donaldson')
INSERT INTO `authors` VALUES('456','Belva Plain')
INSERT INTO `authors` VALUES('457','Robert S. Levinson')
INSERT INTO `authors` VALUES('458','ROBERT S. MCELVAINE')
INSERT INTO `authors` VALUES('459','Roberto Vecchioni')
INSERT INTO `authors` VALUES('460','Gerald Stern')
INSERT INTO `authors` VALUES('461','Jack Canfield')
INSERT INTO `authors` VALUES('462','Charles de Lint')
INSERT INTO `authors` VALUES('463','Barry Neil Kaufman')
INSERT INTO `authors` VALUES('464','David M. Gitlitz')
INSERT INTO `authors` VALUES('465','Muriel Whitaker')
INSERT INTO `authors` VALUES('466','Cokie Roberts')
INSERT INTO `authors` VALUES('467','Andrew L. Johnson')
INSERT INTO `authors` VALUES('468','H. P. Lovecraft')
INSERT INTO `authors` VALUES('469','Helen Myers')
INSERT INTO `authors` VALUES('470','Mary-Kate &amp; Ashley Olsen')
INSERT INTO `authors` VALUES('471','Valerie Frankel')
INSERT INTO `authors` VALUES('472','Barbara Vine')
INSERT INTO `authors` VALUES('473','Joan Anderson')
INSERT INTO `authors` VALUES('474','Theodore Beale')
INSERT INTO `authors` VALUES('475','Bernhard Schlink')
INSERT INTO `authors` VALUES('476','Gael Baudino')
INSERT INTO `authors` VALUES('477','V. S. Naipaul')
INSERT INTO `authors` VALUES('478','Diane Duane')
INSERT INTO `authors` VALUES('479','Hilary Bailey')
INSERT INTO `authors` VALUES('480','WALTER CRONKITE')
INSERT INTO `authors` VALUES('481','Christa Wichterich')
INSERT INTO `authors` VALUES('482','Jacqueline Woodson')
INSERT INTO `authors` VALUES('483','John Pascal')
INSERT INTO `authors` VALUES('484','Laura Wolf')
INSERT INTO `authors` VALUES('485','Erich Segal')
INSERT INTO `authors` VALUES('486','Harry Kemelman')
INSERT INTO `authors` VALUES('487','Elmore Leonard')
INSERT INTO `authors` VALUES('488','Robynn Clairday')
INSERT INTO `authors` VALUES('489','Richard Burton')
INSERT INTO `authors` VALUES('490','VLADIMIR NABOKOV')
INSERT INTO `authors` VALUES('491','Marion Zimmer Bradley')
INSERT INTO `authors` VALUES('492','Howard Fast')
INSERT INTO `authors` VALUES('493','Donna Jo Napoli')
INSERT INTO `authors` VALUES('494','FERN MICHAELS')
INSERT INTO `authors` VALUES('495','Larry Katzenstein')
INSERT INTO `authors` VALUES('496','Bruce Wilkinson')
INSERT INTO `authors` VALUES('497','Betsy Byars')
INSERT INTO `authors` VALUES('498','Sue Miller')
INSERT INTO `authors` VALUES('499','STEPHEN R. DONALDSON')
INSERT INTO `authors` VALUES('500','Dorothy Gilman')
INSERT INTO `authors` VALUES('501','K. A. Applegate')
INSERT INTO `authors` VALUES('502','ALEXANDER MCCALL SMITH')
INSERT INTO `authors` VALUES('503','Robert Penn Warren')
INSERT INTO `authors` VALUES('504','John Jakes')
INSERT INTO `authors` VALUES('505','Gary Zukav')
INSERT INTO `authors` VALUES('506','Tim Lahaye')
INSERT INTO `authors` VALUES('507','David Guterson')
INSERT INTO `authors` VALUES('508','Iain Banks')
INSERT INTO `authors` VALUES('509','Arundhati Roy')
INSERT INTO `authors` VALUES('510','Ted Mooney')
INSERT INTO `authors` VALUES('511','William Maples')
INSERT INTO `authors` VALUES('512','MARK HADDON')
INSERT INTO `authors` VALUES('513','Marc Gascoigne')
INSERT INTO `authors` VALUES('514','Bob Thiele')
INSERT INTO `authors` VALUES('515','Michael J. Rosen')
INSERT INTO `authors` VALUES('516','Michael Palmer')
INSERT INTO `authors` VALUES('517','John Irving')
INSERT INTO `authors` VALUES('518','John Mordock')
INSERT INTO `authors` VALUES('519','Loren D. Estleman')
INSERT INTO `authors` VALUES('520','Emma McLaughlin')
INSERT INTO `authors` VALUES('521','Thomas Hauser')
INSERT INTO `authors` VALUES('522','Robert A. Heinlein')
INSERT INTO `authors` VALUES('523','Jessica Fletcher')
INSERT INTO `authors` VALUES('524','Elizabeth Benedict')
INSERT INTO `authors` VALUES('525','Paul Reiser')
INSERT INTO `authors` VALUES('526','Max Lucado')
INSERT INTO `authors` VALUES('527','Patricia Daniels Cornwell')
INSERT INTO `authors` VALUES('528','Bernard King')
INSERT INTO `authors` VALUES('529','Vicenç Villatoro')
INSERT INTO `authors` VALUES('530','EDNA BARKER')
INSERT INTO `authors` VALUES('531','Alan Alexander Milne')
INSERT INTO `authors` VALUES('532','Isaac Bashevis Singer')
INSERT INTO `authors` VALUES('533','Raymond Chandler')
INSERT INTO `authors` VALUES('534','Laura Zigman')
INSERT INTO `authors` VALUES('535','WILLIAM GOLDMAN')
INSERT INTO `authors` VALUES('536','Peter Hoeg')
INSERT INTO `authors` VALUES('537','Alice Sebold')
INSERT INTO `authors` VALUES('538','Kathleen E. Woodiwiss')
INSERT INTO `authors` VALUES('539','Barbara Taylor Bradford')
INSERT INTO `authors` VALUES('540','CARL HIAASEN')
INSERT INTO `authors` VALUES('541','Frank McCourt')
INSERT INTO `authors` VALUES('542','Arnette Lamb')
INSERT INTO `authors` VALUES('543','Robert Westall')
INSERT INTO `authors` VALUES('544','Clive Cussler')
INSERT INTO `authors` VALUES('545','David Sedaris')
INSERT INTO `authors` VALUES('546','Eric Schlosser')
INSERT INTO `authors` VALUES('547','Renan Demirkan')
INSERT INTO `authors` VALUES('548','Anthony J Alessandra')
INSERT INTO `authors` VALUES('549','Patricia C. Wrede')
INSERT INTO `authors` VALUES('550','Jose Ortega Y Gaset')
INSERT INTO `authors` VALUES('551','C.S. Lewis')
INSERT INTO `authors` VALUES('552','Walter P. Wilson')
INSERT INTO `authors` VALUES('553','Adam Lebor')
INSERT INTO `authors` VALUES('554','Gill Farrer-Halls')
INSERT INTO `authors` VALUES('555','Wolfgang Hohlbein')
INSERT INTO `authors` VALUES('556','Paul Auster')
INSERT INTO `authors` VALUES('557','NATALIE GOLDBERG')
INSERT INTO `authors` VALUES('558','Collectif')
INSERT INTO `authors` VALUES('559','John R. Holt')
INSERT INTO `authors` VALUES('560','Larry McMurtry')
INSERT INTO `authors` VALUES('561','Zadie Smith')
INSERT INTO `authors` VALUES('562','Jennifer Crusie')
INSERT INTO `authors` VALUES('563','VONDA MCINTYRE')
INSERT INTO `authors` VALUES('564','KENT HARUF')
INSERT INTO `authors` VALUES('565','Desmond Mpilo Tutu')
INSERT INTO `authors` VALUES('566','David Lodge')
INSERT INTO `authors` VALUES('567','Mark P. O. Morford')
INSERT INTO `authors` VALUES('568','Piers Vitebsky')
INSERT INTO `authors` VALUES('569','Neil Gaiman')
INSERT INTO `authors` VALUES('570','Isobel Bird')
INSERT INTO `authors` VALUES('571','Eugeni Perea Simón')
INSERT INTO `authors` VALUES('572','Valerie Ferguson')
INSERT INTO `authors` VALUES('573','Rachel Roberts')
INSERT INTO `authors` VALUES('574','Elizabeth Adler')
INSERT INTO `authors` VALUES('575','Michel Tournier')
INSERT INTO `authors` VALUES('576','Kirk Kazanjian')
INSERT INTO `authors` VALUES('577','V.S. Naipaul')
INSERT INTO `authors` VALUES('578','Ilona Koidahl')
INSERT INTO `authors` VALUES('579','Annie Proulx')
INSERT INTO `authors` VALUES('580','Marian Babson')
INSERT INTO `authors` VALUES('581','Jennifer Lauck')
INSERT INTO `authors` VALUES('582','LISA GARDNER')
INSERT INTO `authors` VALUES('583','NATHANIEL HAWTHORNE')
INSERT INTO `authors` VALUES('584','Akiba Rubinstein')
INSERT INTO `authors` VALUES('585','Carol Anshaw')
INSERT INTO `authors` VALUES('586','Carmen Rico-Godoy')
INSERT INTO `authors` VALUES('587','Laura J. Mixon')
INSERT INTO `authors` VALUES('588','Liz Trigg')
INSERT INTO `authors` VALUES('589','JOSEPH GIRZONE')
INSERT INTO `authors` VALUES('590','Mark Twain')
INSERT INTO `authors` VALUES('591','Bruce Fries')
INSERT INTO `authors` VALUES('592','David Brin')
INSERT INTO `authors` VALUES('593','Joseph Heller')
INSERT INTO `authors` VALUES('594','Joan Agut')
INSERT INTO `authors` VALUES('595','R. W. Holder')
INSERT INTO `authors` VALUES('596','Stel Pavlou')
INSERT INTO `authors` VALUES('597','John F. Love')
INSERT INTO `authors` VALUES('598','Melissa Bank')
INSERT INTO `authors` VALUES('599','Simon Nye')
INSERT INTO `authors` VALUES('600','Czeslaw Milosz')
INSERT INTO `authors` VALUES('601','Nicholas Sparks')
INSERT INTO `authors` VALUES('602','Joe Hutsko')
INSERT INTO `authors` VALUES('603','Eric Jerome Dickey')
INSERT INTO `authors` VALUES('604','V. A Howard')
INSERT INTO `authors` VALUES('605','Danielle Steel')
INSERT INTO `authors` VALUES('606','Louis Lamour')
INSERT INTO `authors` VALUES('607','Glendon Swarthout')
INSERT INTO `authors` VALUES('608','Linda Goodman')
INSERT INTO `authors` VALUES('609','Nicola Griffith')
INSERT INTO `authors` VALUES('610','Soren Kierkegaard')
INSERT INTO `authors` VALUES('611','DONNA TARTT')
INSERT INTO `authors` VALUES('612','Michael Rips')
INSERT INTO `authors` VALUES('613','Stephen Gazi')
INSERT INTO `authors` VALUES('614','Haruki Murakami')
INSERT INTO `authors` VALUES('615','Lurlene McDaniel')
INSERT INTO `authors` VALUES('616','Audrey Niffenegger')
INSERT INTO `authors` VALUES('617','Fay Weldon')
INSERT INTO `authors` VALUES('618','Terry Brooks')
INSERT INTO `authors` VALUES('619','Lorenzo Carcaterra')
INSERT INTO `authors` VALUES('620','Stephan Jaramillo')
INSERT INTO `authors` VALUES('621','Judith McNaught')
INSERT INTO `authors` VALUES('622','Jan Karon')
INSERT INTO `authors` VALUES('623','Deborah McDowell')
INSERT INTO `authors` VALUES('624','Bruce Sterling')
INSERT INTO `authors` VALUES('625','Carolyne Aarsen')
INSERT INTO `authors` VALUES('626','PATRICIA REILLY GIFF')
INSERT INTO `authors` VALUES('627','Carol Matthews')
INSERT INTO `authors` VALUES('628','Isabel Allende')
INSERT INTO `authors` VALUES('629','JOHN SAUL')
INSERT INTO `authors` VALUES('630','ANNE RICE')
INSERT INTO `authors` VALUES('631','Eric Thompson')
INSERT INTO `authors` VALUES('632','Emily Dickinson')
INSERT INTO `authors` VALUES('633','Ben Mezrich')
INSERT INTO `authors` VALUES('634','Margriet de Moor')
INSERT INTO `authors` VALUES('635','Cheryl Benard')
INSERT INTO `authors` VALUES('636','Katie Fforde')
INSERT INTO `authors` VALUES('637','Samuel Taylor Coleridge')
INSERT INTO `authors` VALUES('638','David Gemmell')
INSERT INTO `authors` VALUES('639','Margaret Weis')
INSERT INTO `authors` VALUES('640','Chuck Palahniuk')
INSERT INTO `authors` VALUES('641','Roald Dahl')
INSERT INTO `authors` VALUES('642','Laura Ingall Wilder')
INSERT INTO `authors` VALUES('643','David Whyte')
INSERT INTO `authors` VALUES('644','Hubert Selby')
INSERT INTO `authors` VALUES('645','Antoni Serra')
INSERT INTO `authors` VALUES('646','Della Rowland')
INSERT INTO `authors` VALUES('647','Simon Mawer')
INSERT INTO `authors` VALUES('648','SANDRA CISNEROS')
INSERT INTO `authors` VALUES('649','Jane Hamilton')
INSERT INTO `authors` VALUES('650','Tom Mula')
INSERT INTO `authors` VALUES('651','Robert G. Allen')
INSERT INTO `authors` VALUES('652','E. J. W. Barber')
INSERT INTO `authors` VALUES('653','Robin Cook')
INSERT INTO `authors` VALUES('654','Frederik Pohl')
INSERT INTO `authors` VALUES('655','Chaim Potok')
INSERT INTO `authors` VALUES('656','Plato')
INSERT INTO `authors` VALUES('657','Shirley Rousseau Murphy')
INSERT INTO `authors` VALUES('658','LTD')
INSERT INTO `authors` VALUES('659','Sam Bobrick')
INSERT INTO `authors` VALUES('660','Margaret Maron')
INSERT INTO `authors` VALUES('661','H. G. Wells')
INSERT INTO `authors` VALUES('662','Antoine de Saint-Exupéry')
INSERT INTO `authors` VALUES('663','Francesca Marciano')
INSERT INTO `authors` VALUES('664','Lynda Madaras')
INSERT INTO `authors` VALUES('665','Kenneth Oppel')
INSERT INTO `authors` VALUES('666','Richard Zimler')
INSERT INTO `authors` VALUES('667','Mary Barnard')
INSERT INTO `authors` VALUES('668','Elizabeth Wurtzel')
INSERT INTO `authors` VALUES('669','James C. Robertson')
INSERT INTO `authors` VALUES('670','Joe Keenan')
INSERT INTO `authors` VALUES('671','Antonio Albanese')
INSERT INTO `authors` VALUES('672','Michael O\'Mara')
INSERT INTO `authors` VALUES('673','Rebecca Wells')
INSERT INTO `authors` VALUES('674','Melody Carlson')
INSERT INTO `authors` VALUES('675','Donald F. Kettl')
INSERT INTO `authors` VALUES('676','Stewart O\'Nan')
INSERT INTO `authors` VALUES('677','Christopher Rice')
INSERT INTO `authors` VALUES('678','Jane Lindskold')
INSERT INTO `authors` VALUES('679','Nora Roberts')
INSERT INTO `authors` VALUES('680','Niccolò Machiavelli')
INSERT INTO `authors` VALUES('681','Marguerite Henry')
INSERT INTO `authors` VALUES('682','Jean Stewart')
INSERT INTO `authors` VALUES('683','JANE SMILEY')
INSERT INTO `authors` VALUES('684','Olivia Goldsmith')
INSERT INTO `authors` VALUES('685','Horacio Vazquez-Rial')
INSERT INTO `authors` VALUES('686','OSCAR WILDE')
INSERT INTO `authors` VALUES('687','Gaby Hauptmann')
INSERT INTO `authors` VALUES('688','T. Coraghessan Boyle')
INSERT INTO `authors` VALUES('689','Richard Peck')
INSERT INTO `authors` VALUES('690','Jack London')
INSERT INTO `authors` VALUES('691','Jonathan Pearce')
INSERT INTO `authors` VALUES('692','Margaret Truman')
INSERT INTO `authors` VALUES('693','Karen Hesse')
INSERT INTO `authors` VALUES('694','Sidney Sheldon')
INSERT INTO `authors` VALUES('695','M. Carme Junyent')
INSERT INTO `authors` VALUES('696','Teresa Southwick')
INSERT INTO `authors` VALUES('697','Michael Marshall')
INSERT INTO `authors` VALUES('698','DAVID EDDINGS')
INSERT INTO `authors` VALUES('699','Michael Crichton')
INSERT INTO `authors` VALUES('700','P.J. O\'Rourke')
INSERT INTO `authors` VALUES('701','Niccolo Machiavelli')
INSERT INTO `authors` VALUES('702','Billie Letts')
INSERT INTO `authors` VALUES('703','Pat Head Summitt')
INSERT INTO `authors` VALUES('704','Paula Polk Lillard')
INSERT INTO `authors` VALUES('705','ARTHUR PHILLIPS')
INSERT INTO `authors` VALUES('706','Kate Chopin')
INSERT INTO `authors` VALUES('707','SOPHIE KINSELLA')
INSERT INTO `authors` VALUES('708','Robert James Waller')
INSERT INTO `authors` VALUES('709','Ellen Gilchrist')
INSERT INTO `authors` VALUES('710','Charlotte Link')
INSERT INTO `authors` VALUES('711','Donald Merriam Allen')
INSERT INTO `authors` VALUES('712','John Milne')
INSERT INTO `authors` VALUES('713','Hans Johannes Hoefer')
INSERT INTO `authors` VALUES('714','Janet Evanovich')
INSERT INTO `authors` VALUES('715','Richard Bausch')
INSERT INTO `authors` VALUES('716','Carolee Brockmann')
INSERT INTO `authors` VALUES('717','Mari Sandoz')
INSERT INTO `authors` VALUES('718','Richard Russo')
INSERT INTO `authors` VALUES('719','Mary O\'Hara')
INSERT INTO `authors` VALUES('720','Arthur Golden')
INSERT INTO `authors` VALUES('721','Jonathan Safran Foer')
INSERT INTO `authors` VALUES('722','Edward John Moreton Drax Plunkett Dunsany')
INSERT INTO `authors` VALUES('723','Adeline Yen Mah')
INSERT INTO `authors` VALUES('724','Tony Hillerman')
INSERT INTO `authors` VALUES('725','J. R. R. Tolkien')
INSERT INTO `authors` VALUES('726','Jane Heller')
INSERT INTO `authors` VALUES('727','Elizabeth Gaskell')
INSERT INTO `authors` VALUES('728','Diane Johnson')
INSERT INTO `authors` VALUES('729','Janet Dailey')
INSERT INTO `authors` VALUES('730','John Grisham')
INSERT INTO `authors` VALUES('731','Amy Tan')
INSERT INTO `authors` VALUES('732','Beverly Cleary')
INSERT INTO `authors` VALUES('733','Ellen Datlow')
INSERT INTO `authors` VALUES('734','David Morrell')
INSERT INTO `authors` VALUES('735','JOHN IRVING')
INSERT INTO `authors` VALUES('736','Alain Stella')
INSERT INTO `authors` VALUES('737','J. M. Barrie')
INSERT INTO `authors` VALUES('738','Michele Morgan')
INSERT INTO `authors` VALUES('739','Ha Jin')
INSERT INTO `authors` VALUES('740','Stuart Woods')
INSERT INTO `authors` VALUES('741','Betty Smith')
INSERT INTO `authors` VALUES('742','Brady Udall')
INSERT INTO `authors` VALUES('743','Susan Wiggs')
INSERT INTO `authors` VALUES('744','IAN MCEWAN')
INSERT INTO `authors` VALUES('745','SUZANNE FISHER STAPLES')
INSERT INTO `authors` VALUES('746','Milena Moser')
INSERT INTO `authors` VALUES('747','Vance Havner')
INSERT INTO `authors` VALUES('748','Emma Donoghue')
INSERT INTO `authors` VALUES('749','Justine Korman')
INSERT INTO `authors` VALUES('750','Ann-Marie MacDonald')
INSERT INTO `authors` VALUES('751','Allen Widome')
INSERT INTO `authors` VALUES('752','Jerome D. Salinger')
INSERT INTO `authors` VALUES('753','George Gately')
INSERT INTO `authors` VALUES('754','John McEnroe')
INSERT INTO `authors` VALUES('755','Adele Lang')
INSERT INTO `authors` VALUES('756','Harper Lee')
INSERT INTO `authors` VALUES('757','Scott Spencer')
INSERT INTO `authors` VALUES('758','George Orwell')
INSERT INTO `authors` VALUES('759','Patricia D. Cornwell')
INSERT INTO `authors` VALUES('760','C. S. Lewis')
INSERT INTO `authors` VALUES('761','CLARE NAYLOR')
INSERT INTO `authors` VALUES('762','Jeanne Ray')
INSERT INTO `authors` VALUES('763','James Lee Burke')
INSERT INTO `authors` VALUES('764','ALLAN ZOLA KRONZEK')
INSERT INTO `authors` VALUES('765','E. L. Doctorow')
INSERT INTO `authors` VALUES('766','Paul Lester')
INSERT INTO `authors` VALUES('767','Michael Connelly')
INSERT INTO `authors` VALUES('768','Colleen McCullough')
INSERT INTO `authors` VALUES('769','Rena Kornreich Gelissen')
INSERT INTO `authors` VALUES('770','Lynn S. Hightower')
INSERT INTO `authors` VALUES('771','David Feldman')
INSERT INTO `authors` VALUES('772','Leslie Feinberg')
INSERT INTO `authors` VALUES('773','Michael Chabon')
INSERT INTO `authors` VALUES('774','Stephen Chbosky')
INSERT INTO `authors` VALUES('775','ANNA QUINDLEN')
INSERT INTO `authors` VALUES('776','John Varley')
INSERT INTO `authors` VALUES('777','Florence King')
INSERT INTO `authors` VALUES('778','Don DeLillo')
INSERT INTO `authors` VALUES('779','Charles Webb')
INSERT INTO `authors` VALUES('780','Anne Tyler')
INSERT INTO `authors` VALUES('781','Mil Millington')
INSERT INTO `authors` VALUES('782','Suzanne G. Farnham')
INSERT INTO `authors` VALUES('783','David Adams Richards')
INSERT INTO `authors` VALUES('784','Moveon')
INSERT INTO `authors` VALUES('785','Sarah Waters')
INSERT INTO `authors` VALUES('786','Christopher Finch')
INSERT INTO `authors` VALUES('787','Warren W. Wiersbe')
INSERT INTO `authors` VALUES('788','DR SEUSS')
INSERT INTO `authors` VALUES('789','Christopher Moore')
INSERT INTO `authors` VALUES('790','Marvin Miller')
INSERT INTO `authors` VALUES('791','Jen Banbury')
INSERT INTO `authors` VALUES('792','Sarah Orne Jewett')
INSERT INTO `authors` VALUES('793','DAVID MITCHELL')
INSERT INTO `authors` VALUES('794','Elena Ferrante')
INSERT INTO `authors` VALUES('795','Lewis')
INSERT INTO `authors` VALUES('796','Thomas Cahill')
INSERT INTO `authors` VALUES('797','E. B. White')
INSERT INTO `authors` VALUES('798','John Lawton')
INSERT INTO `authors` VALUES('799','Jacqueline L. Tobin')
INSERT INTO `authors` VALUES('800','Jane McCafferty')
INSERT INTO `authors` VALUES('801','Alice Hoffman')
INSERT INTO `authors` VALUES('802','Sandra Dallas')
INSERT INTO `authors` VALUES('803','Barbara Kingsolver')
INSERT INTO `authors` VALUES('804','Irene Gonzalez Frei')
INSERT INTO `authors` VALUES('805','Sue Monk Kidd')
INSERT INTO `authors` VALUES('806','Sten Nadolny')
