INSERT INTO `publishers` VALUES('0','Harvest Books')
INSERT INTO `publishers` VALUES('1','Access Press (HarperCollins)')
INSERT INTO `publishers` VALUES('2','Delacorte Books for Young Readers')
INSERT INTO `publishers` VALUES('3','Michael Joseph Ltd')
INSERT INTO `publishers` VALUES('4','Houghton Mifflin Company')
INSERT INTO `publishers` VALUES('5','Presses Pocket French')
INSERT INTO `publishers` VALUES('6','Bantam Books')
INSERT INTO `publishers` VALUES('7','Llewellyn Publications')
INSERT INTO `publishers` VALUES('8','Little Brown &amp; Company')
INSERT INTO `publishers` VALUES('9','Ullstein Tb')
INSERT INTO `publishers` VALUES('10','Golden Books Publishing Company')
INSERT INTO `publishers` VALUES('11','W W Norton &amp; Co Inc')
INSERT INTO `publishers` VALUES('12','Too Far')
INSERT INTO `publishers` VALUES('13','Scholastic')
INSERT INTO `publishers` VALUES('14','HarperSanFrancisco')
INSERT INTO `publishers` VALUES('15','Childrens Press')
INSERT INTO `publishers` VALUES('16','Wizards of the Coast')
INSERT INTO `publishers` VALUES('17','Abacus')
INSERT INTO `publishers` VALUES('18','Jossey-Bass')
INSERT INTO `publishers` VALUES('19','Schocken Books')
INSERT INTO `publishers` VALUES('20','Perennial')
INSERT INTO `publishers` VALUES('21','HarperTrophy')
INSERT INTO `publishers` VALUES('22','Edizioni E/O')
INSERT INTO `publishers` VALUES('23','Amereon Limited')
INSERT INTO `publishers` VALUES('24','Winedale Publishing')
INSERT INTO `publishers` VALUES('25','Baldini&amp;Castoldi')
INSERT INTO `publishers` VALUES('26','Delta')
INSERT INTO `publishers` VALUES('27','Rowohlt Tb.')
INSERT INTO `publishers` VALUES('28','MacMillan Publishing Company.')
INSERT INTO `publishers` VALUES('29','Troll Communications Llc')
INSERT INTO `publishers` VALUES('30','LGF')
INSERT INTO `publishers` VALUES('31','Pantheon')
INSERT INTO `publishers` VALUES('32','McGraw-Hill')
INSERT INTO `publishers` VALUES('33','AuthorsOmniscient Publishers')
INSERT INTO `publishers` VALUES('34','Faber Children\'s Books')
INSERT INTO `publishers` VALUES('35','Andrew Scott Publishers')
INSERT INTO `publishers` VALUES('36','Random House Value Publishing')
INSERT INTO `publishers` VALUES('37','Mira Books')
INSERT INTO `publishers` VALUES('38','HarperFestival')
INSERT INTO `publishers` VALUES('39','Farrar Straus Giroux')
INSERT INTO `publishers` VALUES('40','Onyx Books')
INSERT INTO `publishers` VALUES('41','HarperEntertainment')
INSERT INTO `publishers` VALUES('42','Henry Holt &amp; Company')
INSERT INTO `publishers` VALUES('43','University of California Press')
INSERT INTO `publishers` VALUES('44','Brockhampton Press')
INSERT INTO `publishers` VALUES('45','Diogenes Verlag')
INSERT INTO `publishers` VALUES('46','Andrews McMeel Publishing')
INSERT INTO `publishers` VALUES('47','Prentice Hall (K-12)')
INSERT INTO `publishers` VALUES('48','Knopf Books for Young Readers')
INSERT INTO `publishers` VALUES('49','Ivy Books')
INSERT INTO `publishers` VALUES('50','Putnam Pub Group')
INSERT INTO `publishers` VALUES('51','Plaza &amp; Janés')
INSERT INTO `publishers` VALUES('52','Eos')
INSERT INTO `publishers` VALUES('53','Cypress House')
INSERT INTO `publishers` VALUES('54','Free Press')
INSERT INTO `publishers` VALUES('55','MTV')
INSERT INTO `publishers` VALUES('56','Simon &amp; Schuster')
INSERT INTO `publishers` VALUES('57','Broadway')
INSERT INTO `publishers` VALUES('58','Little Brown and Company')
INSERT INTO `publishers` VALUES('59','New York Review of Books')
INSERT INTO `publishers` VALUES('60','Speed Graphics')
INSERT INTO `publishers` VALUES('61','Infinity Publishing.com')
INSERT INTO `publishers` VALUES('62','Deutscher Taschenbuch Verlag')
INSERT INTO `publishers` VALUES('63','Editorial Empúries')
INSERT INTO `publishers` VALUES('64','Ediciones Temas de Hoy')
INSERT INTO `publishers` VALUES('65','Multnomah')
INSERT INTO `publishers` VALUES('66','Harper Collins - UK')
INSERT INTO `publishers` VALUES('67','Tor Books')
INSERT INTO `publishers` VALUES('68','Stonewall Inn Editions')
INSERT INTO `publishers` VALUES('69','Salamandra')
INSERT INTO `publishers` VALUES('70','Pearson Education')
INSERT INTO `publishers` VALUES('71','Area')
INSERT INTO `publishers` VALUES('72','Girl Press')
INSERT INTO `publishers` VALUES('73','Pages Publishing Group')
INSERT INTO `publishers` VALUES('74','Black Sparrow Books')
INSERT INTO `publishers` VALUES('75','Barnes Noble Books')
INSERT INTO `publishers` VALUES('76','Vintage Books USA')
INSERT INTO `publishers` VALUES('77','Amber-Allen Publishing')
INSERT INTO `publishers` VALUES('78','Edicions 62')
INSERT INTO `publishers` VALUES('79','W.W. Norton &amp; Company')
INSERT INTO `publishers` VALUES('80','Palgrave-Macmillan')
INSERT INTO `publishers` VALUES('81','W. Morrow')
INSERT INTO `publishers` VALUES('82','Artisan Publishers')
INSERT INTO `publishers` VALUES('83','Teamcom Books')
INSERT INTO `publishers` VALUES('84','Houghton Mifflin Co')
INSERT INTO `publishers` VALUES('85','National Geographic Society')
INSERT INTO `publishers` VALUES('86','St. Martin\'s Paperbacks')
INSERT INTO `publishers` VALUES('87','Crimeline')
INSERT INTO `publishers` VALUES('88','Piper')
INSERT INTO `publishers` VALUES('89','Oxford University Press')
INSERT INTO `publishers` VALUES('90','Aufbau Tb')
INSERT INTO `publishers` VALUES('91','Random House Childrens Books')
INSERT INTO `publishers` VALUES('92','Fawcett')
INSERT INTO `publishers` VALUES('93','Love Spell')
INSERT INTO `publishers` VALUES('94','Penguin Books Ltd')
INSERT INTO `publishers` VALUES('95','Bantam')
INSERT INTO `publishers` VALUES('96','Everyman\'s Library')
INSERT INTO `publishers` VALUES('97','Puffin Books')
INSERT INTO `publishers` VALUES('98','Magic Carpet Books')
INSERT INTO `publishers` VALUES('99','Anchor')
INSERT INTO `publishers` VALUES('100','Bantam Dell Pub Group')
INSERT INTO `publishers` VALUES('101','Silhouette')
INSERT INTO `publishers` VALUES('102','Laurel-Leaf Books')
INSERT INTO `publishers` VALUES('103','Nan A. Talese')
INSERT INTO `publishers` VALUES('104','Morehouse Group')
INSERT INTO `publishers` VALUES('105','Canongate Books Ltd')
INSERT INTO `publishers` VALUES('106','Candlewick Press (MA)')
INSERT INTO `publishers` VALUES('107','Fabbri - RCS Libri')
INSERT INTO `publishers` VALUES('108','Hackett Publishing Company')
INSERT INTO `publishers` VALUES('109','Dreamhaven Books')
INSERT INTO `publishers` VALUES('110','Harpercollins Publisher')
INSERT INTO `publishers` VALUES('111','Emblem Editions')
INSERT INTO `publishers` VALUES('112','Scribner')
INSERT INTO `publishers` VALUES('113','Distribooks')
INSERT INTO `publishers` VALUES('114','Warner Books')
INSERT INTO `publishers` VALUES('115','Alianza')
INSERT INTO `publishers` VALUES('116','Windstorm Creative')
INSERT INTO `publishers` VALUES('117','Arcade Publishing')
INSERT INTO `publishers` VALUES('118','Reader\'s Digest')
INSERT INTO `publishers` VALUES('119','Viking Children\'s Books')
INSERT INTO `publishers` VALUES('120','Del Rey Books')
INSERT INTO `publishers` VALUES('121','St. Martin\'s Minotaur')
INSERT INTO `publishers` VALUES('122','Harpercollins')
INSERT INTO `publishers` VALUES('123','Kiepenheuer &amp; Witsch')
INSERT INTO `publishers` VALUES('124','Putnam Pub Group (Paper)')
INSERT INTO `publishers` VALUES('125','House of Anansi Press')
INSERT INTO `publishers` VALUES('126','Image')
INSERT INTO `publishers` VALUES('127','Pleasant Company Publications')
INSERT INTO `publishers` VALUES('128','Monarch Books')
INSERT INTO `publishers` VALUES('129','Pocket')
INSERT INTO `publishers` VALUES('130','Vintage')
INSERT INTO `publishers` VALUES('131','Kidsbooks.Com')
INSERT INTO `publishers` VALUES('132','Penguin Books')
INSERT INTO `publishers` VALUES('133','Einaudi')
INSERT INTO `publishers` VALUES('134','Landoll')
INSERT INTO `publishers` VALUES('135','Reston Pub. Co')
INSERT INTO `publishers` VALUES('136','Aladdin')
INSERT INTO `publishers` VALUES('137','Riverhead Books')
INSERT INTO `publishers` VALUES('138','Avon Trade')
INSERT INTO `publishers` VALUES('139','Orb Books')
INSERT INTO `publishers` VALUES('140','Bantam Dell Publishing Group')
INSERT INTO `publishers` VALUES('141','Quest Books')
INSERT INTO `publishers` VALUES('142','Random House Trade Paperbacks')
INSERT INTO `publishers` VALUES('143','Trafalgar Square')
INSERT INTO `publishers` VALUES('144','HarperCollins Publishers')
INSERT INTO `publishers` VALUES('145','Egmont Childrens Books')
INSERT INTO `publishers` VALUES('146','Pan Macmillan')
INSERT INTO `publishers` VALUES('147','Downtown Book Center')
INSERT INTO `publishers` VALUES('148','Knopf')
INSERT INTO `publishers` VALUES('149','Watson-Guptill Publications')
INSERT INTO `publishers` VALUES('150','Saunders College Publishing')
INSERT INTO `publishers` VALUES('151','Thomas Nelson')
INSERT INTO `publishers` VALUES('152','Four Walls Eight Windows')
INSERT INTO `publishers` VALUES('153','1stBooks Library')
INSERT INTO `publishers` VALUES('154','Alfred A. Knopf')
INSERT INTO `publishers` VALUES('155','Editorial Laia')
INSERT INTO `publishers` VALUES('156','Berkley Publishing Group')
INSERT INTO `publishers` VALUES('157','MacAdam/Cage Publishing')
INSERT INTO `publishers` VALUES('158','William Morrow')
INSERT INTO `publishers` VALUES('159','Jump at the Sun')
INSERT INTO `publishers` VALUES('160','Mira')
INSERT INTO `publishers` VALUES('161','Fireside')
INSERT INTO `publishers` VALUES('162','Press Gang Publishers')
INSERT INTO `publishers` VALUES('163','Simon Schuster Trade')
INSERT INTO `publishers` VALUES('164','Harlequin')
INSERT INTO `publishers` VALUES('165','Steeple Hill')
INSERT INTO `publishers` VALUES('166','Sourcebooks Landmark')
INSERT INTO `publishers` VALUES('167','Scribner Paper Fiction')
INSERT INTO `publishers` VALUES('168','Little Brown &amp; Co')
INSERT INTO `publishers` VALUES('169','Distribooks Inc')
INSERT INTO `publishers` VALUES('170','Audioworks')
INSERT INTO `publishers` VALUES('171','Diogenes')
INSERT INTO `publishers` VALUES('172','Red Dress Ink')
INSERT INTO `publishers` VALUES('173','River City Pub')
INSERT INTO `publishers` VALUES('174','Harry N Abrams')
INSERT INTO `publishers` VALUES('175','Harpercollins Juvenile Books')
INSERT INTO `publishers` VALUES('176','G. P. Putnam\'s Sons')
INSERT INTO `publishers` VALUES('177','Crabtree Publishing Company')
INSERT INTO `publishers` VALUES('178','Routledge')
INSERT INTO `publishers` VALUES('179','Farrar Straus &amp; Giroux')
INSERT INTO `publishers` VALUES('180','Delta Systems')
INSERT INTO `publishers` VALUES('181','Pocket Star')
INSERT INTO `publishers` VALUES('182','Griffin Trade Paperback')
INSERT INTO `publishers` VALUES('183','Random House Canada')
INSERT INTO `publishers` VALUES('184','Flammarion')
INSERT INTO `publishers` VALUES('185','Hyperion Press')
INSERT INTO `publishers` VALUES('186','Heyne')
INSERT INTO `publishers` VALUES('187','Michael O\'Mara Books')
INSERT INTO `publishers` VALUES('188','Gallimard French')
INSERT INTO `publishers` VALUES('189','Edicoes Asa')
INSERT INTO `publishers` VALUES('190','Tusquets')
INSERT INTO `publishers` VALUES('191','Plume')
INSERT INTO `publishers` VALUES('192','Signet Book')
INSERT INTO `publishers` VALUES('193','Faber Faber Inc')
INSERT INTO `publishers` VALUES('194','I Books')
INSERT INTO `publishers` VALUES('195','HarperTorch')
INSERT INTO `publishers` VALUES('196','Scholastic Paperbacks')
INSERT INTO `publishers` VALUES('197','Price Stern Sloan')
INSERT INTO `publishers` VALUES('198','Diamond Books (NY)')
INSERT INTO `publishers` VALUES('199','Random House Books for Young Readers')
INSERT INTO `publishers` VALUES('200','Pocket Books')
INSERT INTO `publishers` VALUES('201','Laia')
INSERT INTO `publishers` VALUES('202','Ryland Peters &amp; Small Ltd')
INSERT INTO `publishers` VALUES('203','HarperFlamingo Canada')
INSERT INTO `publishers` VALUES('204','Seuil')
INSERT INTO `publishers` VALUES('205','Modern Library')
INSERT INTO `publishers` VALUES('206','Celestial Arts')
INSERT INTO `publishers` VALUES('207','Anchor Pub')
INSERT INTO `publishers` VALUES('208','Signet')
INSERT INTO `publishers` VALUES('209','Washington Square Press')
INSERT INTO `publishers` VALUES('210','Tor Fantasy')
INSERT INTO `publishers` VALUES('211','Ace Books')
INSERT INTO `publishers` VALUES('212','Hackett Pub Co Inc')
INSERT INTO `publishers` VALUES('213','Harcourt')
INSERT INTO `publishers` VALUES('214','Penguin Putnam~trade')
INSERT INTO `publishers` VALUES('215','Roc')
INSERT INTO `publishers` VALUES('216','Villard Books')
INSERT INTO `publishers` VALUES('217','St. Martin\'s Griffin')
INSERT INTO `publishers` VALUES('218','HarperPerennial')
INSERT INTO `publishers` VALUES('219','Lamuv')
INSERT INTO `publishers` VALUES('220','Viking Books')
INSERT INTO `publishers` VALUES('221','University Press of America')
INSERT INTO `publishers` VALUES('222','Regan Books')
INSERT INTO `publishers` VALUES('223','John Wiley &amp; Sons Inc')
INSERT INTO `publishers` VALUES('224','Star Trek')
INSERT INTO `publishers` VALUES('225','Alyson Books')
INSERT INTO `publishers` VALUES('226','W Publishing Group')
INSERT INTO `publishers` VALUES('227','Random House Children\'s Books')
INSERT INTO `publishers` VALUES('228','Wendy Lamb Books')
INSERT INTO `publishers` VALUES('229','NavPress')
INSERT INTO `publishers` VALUES('230','Infinity Publishing (PA)')
INSERT INTO `publishers` VALUES('231','Atlantic Monthly Press')
INSERT INTO `publishers` VALUES('232','Push')
INSERT INTO `publishers` VALUES('233','Edicions de la Magrana')
INSERT INTO `publishers` VALUES('234','Akashic Books')
INSERT INTO `publishers` VALUES('235','Ediciones B')
INSERT INTO `publishers` VALUES('236','Puffin')
INSERT INTO `publishers` VALUES('237','Lomond Books')
INSERT INTO `publishers` VALUES('238','O. W. Barth Bei Scherz')
INSERT INTO `publishers` VALUES('239','Alyson Publications')
INSERT INTO `publishers` VALUES('240','Signet Classics')
INSERT INTO `publishers` VALUES('241','Readers Digest')
INSERT INTO `publishers` VALUES('242','Atheneum')
INSERT INTO `publishers` VALUES('243','Del Rey')
INSERT INTO `publishers` VALUES('244','New English Library')
INSERT INTO `publishers` VALUES('245','Forge Books')
INSERT INTO `publishers` VALUES('246','Jove Books')
INSERT INTO `publishers` VALUES('247','Trafalgar Square Books')
INSERT INTO `publishers` VALUES('248','Mariner Books')
INSERT INTO `publishers` VALUES('249','Kensington Publishing Corp.')
INSERT INTO `publishers` VALUES('250','Spectra Books')
INSERT INTO `publishers` VALUES('251','Tor Books (Mm)')
INSERT INTO `publishers` VALUES('252','Del Sol Press')
INSERT INTO `publishers` VALUES('253','J\'ai lu')
INSERT INTO `publishers` VALUES('254','Fawcett Books')
INSERT INTO `publishers` VALUES('255','HarperCollins')
INSERT INTO `publishers` VALUES('256','Rising Tide Press (AZ)')
INSERT INTO `publishers` VALUES('257','Inner Ocean Publishing')
INSERT INTO `publishers` VALUES('258','Ohio University Press')
INSERT INTO `publishers` VALUES('259','Wings')
INSERT INTO `publishers` VALUES('260','Harmony')
INSERT INTO `publishers` VALUES('261','Readers Digest Assn')
INSERT INTO `publishers` VALUES('262','Yearling')
INSERT INTO `publishers` VALUES('263','Playmore Inc. Publishers')
INSERT INTO `publishers` VALUES('264','Harper Mass Market Paperbacks (Mm)')
INSERT INTO `publishers` VALUES('265','WestBow Press')
INSERT INTO `publishers` VALUES('266','Bantam Classics')
INSERT INTO `publishers` VALUES('267','btb')
INSERT INTO `publishers` VALUES('268','Dell')
INSERT INTO `publishers` VALUES('269','Hodder &amp; Stoughton General Division')
INSERT INTO `publishers` VALUES('270','Manning Publications')
INSERT INTO `publishers` VALUES('271','Beacon Press')
INSERT INTO `publishers` VALUES('272','Baker Book House')
INSERT INTO `publishers` VALUES('273','Union générale d\'éditions')
INSERT INTO `publishers` VALUES('274','Pub Group West')
INSERT INTO `publishers` VALUES('275','Tyndale House Publishers')
INSERT INTO `publishers` VALUES('276','Mysterious Press')
INSERT INTO `publishers` VALUES('277','Harper Mass Market Paperbacks')
INSERT INTO `publishers` VALUES('278','Broadway Books')
INSERT INTO `publishers` VALUES('279','Ferguson Publishing Company')
INSERT INTO `publishers` VALUES('280','Hyperion')
INSERT INTO `publishers` VALUES('281','Dial Books')
INSERT INTO `publishers` VALUES('282','Shambhala')
INSERT INTO `publishers` VALUES('283','Sagebrush Bound')
INSERT INTO `publishers` VALUES('284','St Martins Pr')
INSERT INTO `publishers` VALUES('285','Random House Inc')
INSERT INTO `publishers` VALUES('286','W W Norton &amp; Co')
INSERT INTO `publishers` VALUES('287','Grove Press')
INSERT INTO `publishers` VALUES('288','McClelland &amp; Stewart')
INSERT INTO `publishers` VALUES('289','Bantam Doubleday Dell')
INSERT INTO `publishers` VALUES('290','Hyperion Books for Children')
INSERT INTO `publishers` VALUES('291','University of Nebraska Press')
INSERT INTO `publishers` VALUES('292','Back Bay Books')
INSERT INTO `publishers` VALUES('293','Adams Media Corp')
INSERT INTO `publishers` VALUES('294','Golden Books')
INSERT INTO `publishers` VALUES('295','Picador')
INSERT INTO `publishers` VALUES('296','Plume Books')
INSERT INTO `publishers` VALUES('297','Atria')
INSERT INTO `publishers` VALUES('298','Citadel Press')
INSERT INTO `publishers` VALUES('299','Pantheon Books')
INSERT INTO `publishers` VALUES('300','Delacorte Press')
INSERT INTO `publishers` VALUES('301','Rowohlt')
INSERT INTO `publishers` VALUES('302','Touchstone')
INSERT INTO `publishers` VALUES('303','Picador USA')
INSERT INTO `publishers` VALUES('304','Picador (UK)')
INSERT INTO `publishers` VALUES('305','Regal Books')
INSERT INTO `publishers` VALUES('306','St. Martin\'s Press')
INSERT INTO `publishers` VALUES('307','Sunflower Press')
INSERT INTO `publishers` VALUES('308','David R. Godine Publisher')
INSERT INTO `publishers` VALUES('309','Zebra Books')
INSERT INTO `publishers` VALUES('310','Warner Vision')
INSERT INTO `publishers` VALUES('311','Point Fantasy')
INSERT INTO `publishers` VALUES('312','Dover Publications')
INSERT INTO `publishers` VALUES('313','White Pine Press (NY)')
INSERT INTO `publishers` VALUES('314','Southwater Publishing')
INSERT INTO `publishers` VALUES('315','YWAM Publishing')
INSERT INTO `publishers` VALUES('316','Livre de Poche')
INSERT INTO `publishers` VALUES('317','Lectorum Pubns (J)')
INSERT INTO `publishers` VALUES('318','Putnam Publishing Group')
INSERT INTO `publishers` VALUES('319','New Directions Publishing Corporation')
INSERT INTO `publishers` VALUES('320','Simon &amp; Schuster (Trade Division)')
INSERT INTO `publishers` VALUES('321','Soho Press')
INSERT INTO `publishers` VALUES('322','Dtv')
INSERT INTO `publishers` VALUES('323','Taschen Verlag')
INSERT INTO `publishers` VALUES('324','Three Rivers Press')
INSERT INTO `publishers` VALUES('325','L�?¼bbe')
INSERT INTO `publishers` VALUES('326','Columna')
INSERT INTO `publishers` VALUES('327','Noble House')
INSERT INTO `publishers` VALUES('328','Phoenix Books')
INSERT INTO `publishers` VALUES('329','Harpercollins Library')
INSERT INTO `publishers` VALUES('330','The Lyons Press')
INSERT INTO `publishers` VALUES('331','Ecco Press')
INSERT INTO `publishers` VALUES('332','Livre De Poche French')
INSERT INTO `publishers` VALUES('333','Doubleday Books')
INSERT INTO `publishers` VALUES('334','Miramax')
INSERT INTO `publishers` VALUES('335','Epicenter Press')
INSERT INTO `publishers` VALUES('336','Editech Pr')
INSERT INTO `publishers` VALUES('337','Scholastic Paperbacks (Mm)')
INSERT INTO `publishers` VALUES('338','Scholastic Inc')
INSERT INTO `publishers` VALUES('339','Buy Books on the web.com')
INSERT INTO `publishers` VALUES('340','Last Knight Pub Co')
INSERT INTO `publishers` VALUES('341','Alpha Books')
INSERT INTO `publishers` VALUES('342','Natl Book Network')
INSERT INTO `publishers` VALUES('343','Atria Books')
INSERT INTO `publishers` VALUES('344','Chambers Harrap Publishers Ltd')
INSERT INTO `publishers` VALUES('345','Warner Books (Mm)')
INSERT INTO `publishers` VALUES('346','Hal Leonard Corp')
INSERT INTO `publishers` VALUES('347','Penguin USA (Paper)')
INSERT INTO `publishers` VALUES('348','Viking Juvenile')
INSERT INTO `publishers` VALUES('349','Goldmann')
INSERT INTO `publishers` VALUES('350','Avon Books')
INSERT INTO `publishers` VALUES('351','Laurel Leaf')
INSERT INTO `publishers` VALUES('352','Crown')
INSERT INTO `publishers` VALUES('353','Owl Books')
INSERT INTO `publishers` VALUES('354','Dutton Books')
INSERT INTO `publishers` VALUES('355','Dark Horse Comics')
INSERT INTO `publishers` VALUES('356','Anagrama')
INSERT INTO `publishers` VALUES('357','Dell Publishing Company')
INSERT INTO `publishers` VALUES('358','Brilliance Audio - Trade')
INSERT INTO `publishers` VALUES('359','Minotauro')
INSERT INTO `publishers` VALUES('360','Gulf Publishing Company')
INSERT INTO `publishers` VALUES('361','NTC/Contemporary Publishing Company')
INSERT INTO `publishers` VALUES('362','Gallimard')
INSERT INTO `publishers` VALUES('363','W. W. Norton &amp; Company')
INSERT INTO `publishers` VALUES('364','Laure Leaf')
INSERT INTO `publishers` VALUES('365','Ballantine Books')
INSERT INTO `publishers` VALUES('366','Destino')
INSERT INTO `publishers` VALUES('367','Pinnacle Books')
INSERT INTO `publishers` VALUES('368','Starfire')
INSERT INTO `publishers` VALUES('369','Penguin Putnam~mass')
INSERT INTO `publishers` VALUES('370','Castle Books')
INSERT INTO `publishers` VALUES('371','Hanser')
INSERT INTO `publishers` VALUES('372','Doubleday')
INSERT INTO `publishers` VALUES('373','HarperPrism')
INSERT INTO `publishers` VALUES('374','Douglas Gibson Books')
INSERT INTO `publishers` VALUES('375','Quill (HarperCollins)')
INSERT INTO `publishers` VALUES('376','Dearborn Financial Publishing')
INSERT INTO `publishers` VALUES('377','Thorndike Pr')
INSERT INTO `publishers` VALUES('378','Hill &amp; Wang')
INSERT INTO `publishers` VALUES('379','Health Communications')
INSERT INTO `publishers` VALUES('380','Word Publishing')
INSERT INTO `publishers` VALUES('381','Spectra')
INSERT INTO `publishers` VALUES('382','F.J. Moody')
INSERT INTO `publishers` VALUES('383','Bloomsbury Pub Ltd')
INSERT INTO `publishers` VALUES('384','F. H. Revell')
INSERT INTO `publishers` VALUES('385','Island')
INSERT INTO `publishers` VALUES('386','New Amer Library')
INSERT INTO `publishers` VALUES('387','Main Street Books')
INSERT INTO `publishers` VALUES('388','Avon')
INSERT INTO `publishers` VALUES('389','Yearling Books')
INSERT INTO `publishers` VALUES('390','Arcadia Books')
INSERT INTO `publishers` VALUES('391','Deutscher Taschenbuch Verlag (DTV)')
INSERT INTO `publishers` VALUES('392','Random House')
INSERT INTO `publishers` VALUES('393','Thomas Dunne Books')
INSERT INTO `publishers` VALUES('394','Bloomsbury Publishing PLC')
INSERT INTO `publishers` VALUES('395','Chatto &amp; Windus')
INSERT INTO `publishers` VALUES('396','Penguin USA')
INSERT INTO `publishers` VALUES('397','Firebrand Books')
