INSERT INTO `authors` VALUES ('0','Tami Hoag');
INSERT INTO `authors` VALUES ('1','David Iglehart');
INSERT INTO `authors` VALUES ('2','Paul Lester');
INSERT INTO `authors` VALUES ('3','Irving. Adler');
INSERT INTO `authors` VALUES ('4','Niccol Machiavelli');
INSERT INTO `authors` VALUES ('5','Ursula Hegi');
INSERT INTO `authors` VALUES ('6','John Lawton');
INSERT INTO `authors` VALUES ('7','Andrew Clements');
INSERT INTO `authors` VALUES ('8','Robert Lacey');
INSERT INTO `authors` VALUES ('9','Norman Bridwell');
INSERT INTO `authors` VALUES ('10','Anita Shreve');
INSERT INTO `authors` VALUES ('11','Diane Duane');
INSERT INTO `authors` VALUES ('12','Robert S. Mcelvaine');
INSERT INTO `authors` VALUES ('13','William Trevor');
INSERT INTO `authors` VALUES ('14','Beverly Cleary');
INSERT INTO `authors` VALUES ('15','Desmond Mpilo Tutu');
INSERT INTO `authors` VALUES ('16','R. J. Kaiser');
INSERT INTO `authors` VALUES ('17','C. Baudelaire');
INSERT INTO `authors` VALUES ('18','Oflia Dracs');
INSERT INTO `authors` VALUES ('19','Laura J. Mixon');
INSERT INTO `authors` VALUES ('20','Ray Bradbury');
INSERT INTO `authors` VALUES ('21','J. R. R. Tolkien');
INSERT INTO `authors` VALUES ('22','Tanuja Desai Hidier');
INSERT INTO `authors` VALUES ('23','Billie Letts');
INSERT INTO `authors` VALUES ('24','Steve Thayer');
INSERT INTO `authors` VALUES ('25','Joseph Girzone');
INSERT INTO `authors` VALUES ('26','Sophie Kinsella');
INSERT INTO `authors` VALUES ('27','Suzanne G. Farnham');
INSERT INTO `authors` VALUES ('28','Martin Schenk');
INSERT INTO `authors` VALUES ('29','John Saul');
INSERT INTO `authors` VALUES ('30','Barbara Michaels');
INSERT INTO `authors` VALUES ('31','Daphne Du Maurier');
INSERT INTO `authors` VALUES ('32','Michael O\'Mara');
INSERT INTO `authors` VALUES ('33','Michael Chabon');
INSERT INTO `authors` VALUES ('34','Betsy Byars');
INSERT INTO `authors` VALUES ('35','C.S. Lewis');
INSERT INTO `authors` VALUES ('36','Dorothy Allison');
INSERT INTO `authors` VALUES ('37','Lynda Madaras');
INSERT INTO `authors` VALUES ('38','Gerald Stern');
INSERT INTO `authors` VALUES ('39','Milena Moser');
INSERT INTO `authors` VALUES ('40','Laura Wolf');
INSERT INTO `authors` VALUES ('41','Mark Salzman');
INSERT INTO `authors` VALUES ('42','Fannie Flagg');
INSERT INTO `authors` VALUES ('43','Czeslaw Milosz');
INSERT INTO `authors` VALUES ('44','H. G. Wells');
INSERT INTO `authors` VALUES ('45','Lauren Maddison');
INSERT INTO `authors` VALUES ('46','Ernest Hemingway');
INSERT INTO `authors` VALUES ('47','Jane Austen');
INSERT INTO `authors` VALUES ('48','Judith Kelman');
INSERT INTO `authors` VALUES ('49','Milan Kundera');
INSERT INTO `authors` VALUES ('50','Joe Hutsko');
INSERT INTO `authors` VALUES ('51','Sarah Ban Breathnach');
INSERT INTO `authors` VALUES ('52','Linda Lay Shuler');
INSERT INTO `authors` VALUES ('53','Don Delillo');
INSERT INTO `authors` VALUES ('54','Chris Anne Wolfe');
INSERT INTO `authors` VALUES ('55','Bernhard Schlink');
INSERT INTO `authors` VALUES ('56','Ad Hudler');
INSERT INTO `authors` VALUES ('57','Ben Mezrich');
INSERT INTO `authors` VALUES ('58','Adele Lang');
INSERT INTO `authors` VALUES ('59','Gaby Hauptmann');
INSERT INTO `authors` VALUES ('60','Frances Hodgson  Burnett');
INSERT INTO `authors` VALUES ('61','Walter P. Wilson');
INSERT INTO `authors` VALUES ('62','Allen Widome');
INSERT INTO `authors` VALUES ('63','Emma Mclaughlin');
INSERT INTO `authors` VALUES ('64','Paul Monette');
INSERT INTO `authors` VALUES ('65','Frederik Pohl');
INSERT INTO `authors` VALUES ('66','Pat Head Summitt');
INSERT INTO `authors` VALUES ('67','Michael Blake');
INSERT INTO `authors` VALUES ('68','Charles Frazier');
INSERT INTO `authors` VALUES ('69','Jan Karon');
INSERT INTO `authors` VALUES ('70','Jhumpa Lahiri');
INSERT INTO `authors` VALUES ('71','Gabriel Garcia Marquez');
INSERT INTO `authors` VALUES ('72','Lauren Sanders');
INSERT INTO `authors` VALUES ('73','Louis De Bernieres');
INSERT INTO `authors` VALUES ('74','Kate Chopin');
INSERT INTO `authors` VALUES ('75','Matthew Thomas');
INSERT INTO `authors` VALUES ('76','P. D. James');
INSERT INTO `authors` VALUES ('77','Jane Lindskold');
INSERT INTO `authors` VALUES ('78','Tim Dorsey');
INSERT INTO `authors` VALUES ('79','Isabelle Holland');
INSERT INTO `authors` VALUES ('80','John Galsworthy');
INSERT INTO `authors` VALUES ('81','Sandra Levy Ceren');
INSERT INTO `authors` VALUES ('82','Malachy Mccourt');
INSERT INTO `authors` VALUES ('83','Richard Webster');
INSERT INTO `authors` VALUES ('84','H. P. Lovecraft');
INSERT INTO `authors` VALUES ('85','Luis Racionero');
INSERT INTO `authors` VALUES ('86','Tamora Pierce');
INSERT INTO `authors` VALUES ('87','John. Blofeld');
INSERT INTO `authors` VALUES ('88','David Steinman');
INSERT INTO `authors` VALUES ('89','David Baldacci');
INSERT INTO `authors` VALUES ('90','Rene Barjavel');
INSERT INTO `authors` VALUES ('91','Suzanne Fisher Staples');
INSERT INTO `authors` VALUES ('92','Donna Jo Napoli');
INSERT INTO `authors` VALUES ('93','Ted Hughes');
INSERT INTO `authors` VALUES ('94','Robert Westall');
INSERT INTO `authors` VALUES ('95','Karen X. Tulchinsky');
INSERT INTO `authors` VALUES ('96','Richard A. Lupoff');
INSERT INTO `authors` VALUES ('97','William Maples');
INSERT INTO `authors` VALUES ('98','Stephen Chbosky');
INSERT INTO `authors` VALUES ('99','Sylvia Plath');
INSERT INTO `authors` VALUES ('100','Kay Hooper');
INSERT INTO `authors` VALUES ('101','Valerie Frankel');
INSERT INTO `authors` VALUES ('102','Pat Hutchins');
INSERT INTO `authors` VALUES ('103','Elizabeth Laird');
INSERT INTO `authors` VALUES ('104','Zadie Smith');
INSERT INTO `authors` VALUES ('105','Jennifer Crusie');
INSERT INTO `authors` VALUES ('106','Agatha Christie');
INSERT INTO `authors` VALUES ('107','Sue Miller');
INSERT INTO `authors` VALUES ('108','Richard Bausch');
INSERT INTO `authors` VALUES ('109','Carolee Brockmann');
INSERT INTO `authors` VALUES ('110','David Lodge');
INSERT INTO `authors` VALUES ('111','Leon Hale');
INSERT INTO `authors` VALUES ('112','Craig Boldman');
INSERT INTO `authors` VALUES ('113','Mary Higgins Clark');
INSERT INTO `authors` VALUES ('114','Julia Oliver');
INSERT INTO `authors` VALUES ('115','Moveon');
INSERT INTO `authors` VALUES ('116','Charles Sullivan');
INSERT INTO `authors` VALUES ('117','Harry Kemelman');
INSERT INTO `authors` VALUES ('118','Sara Paretsky');
INSERT INTO `authors` VALUES ('119','Karen Hesse');
INSERT INTO `authors` VALUES ('120','J. M. Barrie');
INSERT INTO `authors` VALUES ('121','Harry M. Walker');
INSERT INTO `authors` VALUES ('122','Lois Lowry');
INSERT INTO `authors` VALUES ('123','K. A. Applegate');
INSERT INTO `authors` VALUES ('124','A.S. Byatt');
INSERT INTO `authors` VALUES ('125','Kenneth Oppel');
INSERT INTO `authors` VALUES ('126','E. L. Doctorow');
INSERT INTO `authors` VALUES ('127','Carol J. Farley');
INSERT INTO `authors` VALUES ('128','Ivan Doig');
INSERT INTO `authors` VALUES ('129','Valerie Block');
INSERT INTO `authors` VALUES ('130','Rex Stout');
INSERT INTO `authors` VALUES ('131','Anna Sewell');
INSERT INTO `authors` VALUES ('132','Benjamin Hoff');
INSERT INTO `authors` VALUES ('133','Bram Stoker');
INSERT INTO `authors` VALUES ('134','Karen Stolz');
INSERT INTO `authors` VALUES ('135','Haruki Murakami');
INSERT INTO `authors` VALUES ('136','Arundhati Roy');
INSERT INTO `authors` VALUES ('137','Mark Haddon');
INSERT INTO `authors` VALUES ('138','Marc Reisner');
INSERT INTO `authors` VALUES ('139','George Gately');
INSERT INTO `authors` VALUES ('140','Mercedes Lackey');
INSERT INTO `authors` VALUES ('141','Charles R. Swindoll');
INSERT INTO `authors` VALUES ('142','Christoph Hein');
INSERT INTO `authors` VALUES ('143','George Orwell');
INSERT INTO `authors` VALUES ('144','Samuel Taylor Coleridge');
INSERT INTO `authors` VALUES ('145','Teresa Southwick');
INSERT INTO `authors` VALUES ('146','Melisa Michaels');
INSERT INTO `authors` VALUES ('147','Cheryl Benard');
INSERT INTO `authors` VALUES ('148','Ellen Gilchrist');
INSERT INTO `authors` VALUES ('149','Jean Marzollo');
INSERT INTO `authors` VALUES ('150','Gina Bari Kolata');
INSERT INTO `authors` VALUES ('151','Alain Stella');
INSERT INTO `authors` VALUES ('152','Bernard King');
INSERT INTO `authors` VALUES ('153','Clare Naylor');
INSERT INTO `authors` VALUES ('154','Michael J. Rosen');
INSERT INTO `authors` VALUES ('155','Betty Smith');
INSERT INTO `authors` VALUES ('156','Anthony Trollope');
INSERT INTO `authors` VALUES ('157','Hilary Bailey');
INSERT INTO `authors` VALUES ('158','Mil Millington');
INSERT INTO `authors` VALUES ('159','John Grisham');
INSERT INTO `authors` VALUES ('160','Julie Morgenstern');
INSERT INTO `authors` VALUES ('161','John Pascal');
INSERT INTO `authors` VALUES ('162','Claude Lanzmann');
INSERT INTO `authors` VALUES ('163','H. Norman Wright');
INSERT INTO `authors` VALUES ('164','Leo Tolstoy');
INSERT INTO `authors` VALUES ('165','Ted Mooney');
INSERT INTO `authors` VALUES ('166','Mitch Albom');
INSERT INTO `authors` VALUES ('167','Soren Kierkegaard');
INSERT INTO `authors` VALUES ('168','David Eddings');
INSERT INTO `authors` VALUES ('169','John Bellairs');
INSERT INTO `authors` VALUES ('170','Tanith Lee');
INSERT INTO `authors` VALUES ('171','John Mordock');
INSERT INTO `authors` VALUES ('172','Anne Tyler');
INSERT INTO `authors` VALUES ('173','Bob Shacochis');
INSERT INTO `authors` VALUES ('174','Nicholas Sparks');
INSERT INTO `authors` VALUES ('175','Mary O\'Hara');
INSERT INTO `authors` VALUES ('176','Jack Canfield');
INSERT INTO `authors` VALUES ('177','Patricia D. Cornwell');
INSERT INTO `authors` VALUES ('178','Stephen J. Weininger');
INSERT INTO `authors` VALUES ('179','Jacob Weisberg');
INSERT INTO `authors` VALUES ('180','Max Lucado');
INSERT INTO `authors` VALUES ('181','Isaac Bashevis Singer');
INSERT INTO `authors` VALUES ('182','Justine Korman');
INSERT INTO `authors` VALUES ('183','Bob Sjogren');
INSERT INTO `authors` VALUES ('184','Paul Jennings');
INSERT INTO `authors` VALUES ('185','Joanna Trollope');
INSERT INTO `authors` VALUES ('186','Mark P. O. Morford');
INSERT INTO `authors` VALUES ('187','John A. Keel');
INSERT INTO `authors` VALUES ('188','Iris Johansen');
INSERT INTO `authors` VALUES ('189','Chuck Palahniuk');
INSERT INTO `authors` VALUES ('190','Marc Levy');
INSERT INTO `authors` VALUES ('191','Ann Brashares');
INSERT INTO `authors` VALUES ('192','Edward John Moreton Drax Plunkett Dunsany');
INSERT INTO `authors` VALUES ('193','David Whyte');
INSERT INTO `authors` VALUES ('194','Jennifer Weiner');
INSERT INTO `authors` VALUES ('195','Spalding Gray');
INSERT INTO `authors` VALUES ('196','Tom Robbins');
INSERT INTO `authors` VALUES ('197','Lewis');
INSERT INTO `authors` VALUES ('198','Aleksandr Zinoviev');
INSERT INTO `authors` VALUES ('199','Bruce Sterling');
INSERT INTO `authors` VALUES ('200','T. Coraghessan Boyle');
INSERT INTO `authors` VALUES ('201','Anne Rivers Siddons');
INSERT INTO `authors` VALUES ('202','David Mitchell');
INSERT INTO `authors` VALUES ('203','Ann Rule');
INSERT INTO `authors` VALUES ('204','Emily Dickinson');
INSERT INTO `authors` VALUES ('205','Carmen Rico-Godoy');
INSERT INTO `authors` VALUES ('206','Nevada Barr');
INSERT INTO `authors` VALUES ('207','Joseph Heller');
INSERT INTO `authors` VALUES ('208','Kenneth Grahame');
INSERT INTO `authors` VALUES ('209','Douglas Adams');
INSERT INTO `authors` VALUES ('210','John T. Lescroart');
INSERT INTO `authors` VALUES ('211','Maria Jan');
INSERT INTO `authors` VALUES ('212','Norton Juster');
INSERT INTO `authors` VALUES ('213','R. W. Holder');
INSERT INTO `authors` VALUES ('214','Jack London');
INSERT INTO `authors` VALUES ('215','Erich Segal');
INSERT INTO `authors` VALUES ('216','Mordecai Richler');
INSERT INTO `authors` VALUES ('217','Anne Frasier');
INSERT INTO `authors` VALUES ('218','Anita Diamant');
INSERT INTO `authors` VALUES ('219','Lurlene Mcdaniel');
INSERT INTO `authors` VALUES ('220','William Sleator');
INSERT INTO `authors` VALUES ('221','Charles Webb');
INSERT INTO `authors` VALUES ('222','Niccolo Machiavelli');
INSERT INTO `authors` VALUES ('223','E. J. W. Barber');
INSERT INTO `authors` VALUES ('224','Jeanne Ray');
INSERT INTO `authors` VALUES ('225','Vonda Mcintyre');
INSERT INTO `authors` VALUES ('226','Pam Conrad');
INSERT INTO `authors` VALUES ('227','Susan Grant');
INSERT INTO `authors` VALUES ('228','William Shakespeare');
INSERT INTO `authors` VALUES ('229','Alexander Mccall Smith');
INSERT INTO `authors` VALUES ('230','Lorenzo Carcaterra');
INSERT INTO `authors` VALUES ('231','J. R. Parrish');
INSERT INTO `authors` VALUES ('232','Arnette Lamb');
INSERT INTO `authors` VALUES ('233','Gordon Jarvie');
INSERT INTO `authors` VALUES ('234','Christopher Moore');
INSERT INTO `authors` VALUES ('235','Anna Quindlen');
INSERT INTO `authors` VALUES ('236','Stephan Jaramillo');
INSERT INTO `authors` VALUES ('237','Terry Brooks');
INSERT INTO `authors` VALUES ('238','Mark Cohen');
INSERT INTO `authors` VALUES ('239','P.J. O\'Rourke');
INSERT INTO `authors` VALUES ('240','Tawni O\'Dell');
INSERT INTO `authors` VALUES ('241','Roland Warren');
INSERT INTO `authors` VALUES ('242','Sherry Garland');
INSERT INTO `authors` VALUES ('243','Alain-Fournier');
INSERT INTO `authors` VALUES ('244','Jonathan Safran Foer');
INSERT INTO `authors` VALUES ('245','Arthur Phillips');
INSERT INTO `authors` VALUES ('246','Donna K Grosvenor');
INSERT INTO `authors` VALUES ('247','Jean Giono');
INSERT INTO `authors` VALUES ('248','Josephine Carlton');
INSERT INTO `authors` VALUES ('249','Stephen Mccauley');
INSERT INTO `authors` VALUES ('250','Ferran Torrent');
INSERT INTO `authors` VALUES ('251','Edward Rutherfurd');
INSERT INTO `authors` VALUES ('252','Gael Baudino');
INSERT INTO `authors` VALUES ('253','Lorna Landvik');
INSERT INTO `authors` VALUES ('254','Anne Dingus');
INSERT INTO `authors` VALUES ('255','Sir Arthur Conan Doyle');
INSERT INTO `authors` VALUES ('256','Ken Follett');
INSERT INTO `authors` VALUES ('257','Malcolm Goodway');
INSERT INTO `authors` VALUES ('258','V.S. Naipaul');
INSERT INTO `authors` VALUES ('259','Eric Schlosser');
INSERT INTO `authors` VALUES ('260','Simon Nye');
INSERT INTO `authors` VALUES ('261','A.C. Crispin');
INSERT INTO `authors` VALUES ('262','David G. Hartwell');
INSERT INTO `authors` VALUES ('263','Kristin Hannah');
INSERT INTO `authors` VALUES ('264','Karen Armstrong');
INSERT INTO `authors` VALUES ('265','Catherine Coulter');
INSERT INTO `authors` VALUES ('266','Eileen Yin-Fei Lo');
INSERT INTO `authors` VALUES ('267','Tom Mula');
INSERT INTO `authors` VALUES ('268','Ralph Ellison');
INSERT INTO `authors` VALUES ('269','Julie Campbell');
INSERT INTO `authors` VALUES ('270','Harperreference');
INSERT INTO `authors` VALUES ('271','Donald Merriam Allen');
INSERT INTO `authors` VALUES ('272','The Onion');
INSERT INTO `authors` VALUES ('273','Richard Bach');
INSERT INTO `authors` VALUES ('274','Mike Gayle');
INSERT INTO `authors` VALUES ('275','Antoine De Saint-Exupry');
INSERT INTO `authors` VALUES ('276','Thomas Hauser');
INSERT INTO `authors` VALUES ('277','Janet Dailey');
INSERT INTO `authors` VALUES ('278','John Mcenroe');
INSERT INTO `authors` VALUES ('279','Lauren Haney');
INSERT INTO `authors` VALUES ('280','Isabel-Clara Sim');
INSERT INTO `authors` VALUES ('281','Frank Waters');
INSERT INTO `authors` VALUES ('282','Alain De Botton');
INSERT INTO `authors` VALUES ('283','Jerome D. Salinger');
INSERT INTO `authors` VALUES ('284','Edna Barker');
INSERT INTO `authors` VALUES ('285','John Mortimer');
INSERT INTO `authors` VALUES ('286','Brady Udall');
INSERT INTO `authors` VALUES ('287','Jack Kerouac');
INSERT INTO `authors` VALUES ('288','Donna Tartt');
INSERT INTO `authors` VALUES ('289','A. S. Byatt');
INSERT INTO `authors` VALUES ('290','Peter Straub');
INSERT INTO `authors` VALUES ('291','Candace Bushnell');
INSERT INTO `authors` VALUES ('292','Elmore Leonard');
INSERT INTO `authors` VALUES ('293','Trudy Suggs');
INSERT INTO `authors` VALUES ('294','Florence King');
INSERT INTO `authors` VALUES ('295','Angela Elwell Hunt');
INSERT INTO `authors` VALUES ('296','Patricia C. Wrede');
INSERT INTO `authors` VALUES ('297','A. Manette Ansay');
INSERT INTO `authors` VALUES ('298','Andy Sloss');
INSERT INTO `authors` VALUES ('299','Henry James');
INSERT INTO `authors` VALUES ('300','Erma Bombeck');
INSERT INTO `authors` VALUES ('301','Suzanne Brockmann');
INSERT INTO `authors` VALUES ('302','Frank Mccourt');
INSERT INTO `authors` VALUES ('303','Sam Bobrick');
INSERT INTO `authors` VALUES ('304','E.H. Shepard');
INSERT INTO `authors` VALUES ('305','Tracy Chevalier');
INSERT INTO `authors` VALUES ('306','Armistead Maupin');
INSERT INTO `authors` VALUES ('307','Stuart Woods');
INSERT INTO `authors` VALUES ('308','David Adams Richards');
INSERT INTO `authors` VALUES ('309','Leslie Feinberg');
INSERT INTO `authors` VALUES ('310','Jean Stewart');
INSERT INTO `authors` VALUES ('311','Barry Lopez');
INSERT INTO `authors` VALUES ('312','Judith Guest');
INSERT INTO `authors` VALUES ('313','Hans Johannes Hoefer');
INSERT INTO `authors` VALUES ('314','David Crombie');
INSERT INTO `authors` VALUES ('315','Mary-Kate &Amp; Ashley Olsen');
INSERT INTO `authors` VALUES ('316','Blanche Fisher Wright');
INSERT INTO `authors` VALUES ('317','Rena Kornreich Gelissen');
INSERT INTO `authors` VALUES ('318','Boris Vian');
INSERT INTO `authors` VALUES ('319','Lois Duncan');
INSERT INTO `authors` VALUES ('320','Michael Jan Friedman');
INSERT INTO `authors` VALUES ('321','Dawn Chipman');
INSERT INTO `authors` VALUES ('322','Theodore Beale');
INSERT INTO `authors` VALUES ('323','J.D. Robb');
INSERT INTO `authors` VALUES ('324','Carol Anshaw');
INSERT INTO `authors` VALUES ('325','John F. Love');
INSERT INTO `authors` VALUES ('326','Louis Lamour');
INSERT INTO `authors` VALUES ('327','William Eisner');
INSERT INTO `authors` VALUES ('328','Joseph Conrad');
INSERT INTO `authors` VALUES ('329','Emma Donoghue');
INSERT INTO `authors` VALUES ('330','Michael Slade');
INSERT INTO `authors` VALUES ('331','Christa Wolf');
INSERT INTO `authors` VALUES ('332','Jacquelyn Mitchard');
INSERT INTO `authors` VALUES ('333','Maeve Binchy');
INSERT INTO `authors` VALUES ('334','Wilbur Smith');
INSERT INTO `authors` VALUES ('335','Mary Barnard');
INSERT INTO `authors` VALUES ('336','Gregory Maguire');
INSERT INTO `authors` VALUES ('337','Dog Mary Crow');
INSERT INTO `authors` VALUES ('338','John R. Holt');
INSERT INTO `authors` VALUES ('339','Travis Thrasher');
INSERT INTO `authors` VALUES ('340','Barbara Metzger');
INSERT INTO `authors` VALUES ('341','Antoni Serra');
INSERT INTO `authors` VALUES ('342','Tony Parsons');
INSERT INTO `authors` VALUES ('343','Larry Mcmurtry');
INSERT INTO `authors` VALUES ('344','James Patterson');
INSERT INTO `authors` VALUES ('345','Nicholas Evans');
INSERT INTO `authors` VALUES ('346','James Burke');
INSERT INTO `authors` VALUES ('347','Tom Wolfe');
INSERT INTO `authors` VALUES ('348','Lisa Jackson');
INSERT INTO `authors` VALUES ('349','Valerie Ferguson');
INSERT INTO `authors` VALUES ('350','Andrei Codrescu');
INSERT INTO `authors` VALUES ('351','Maya Angelou');
INSERT INTO `authors` VALUES ('352','Michele Morgan');
INSERT INTO `authors` VALUES ('353','Willa Cather');
INSERT INTO `authors` VALUES ('354','Emily Bronte');
INSERT INTO `authors` VALUES ('355','Deepak Chopra');
INSERT INTO `authors` VALUES ('356','Patricia Cornwell');
INSERT INTO `authors` VALUES ('357','Piers Anthony');
INSERT INTO `authors` VALUES ('358','Philip Ardagh');
INSERT INTO `authors` VALUES ('359','Charles Bukowski');
INSERT INTO `authors` VALUES ('360','Michael Marshall');
INSERT INTO `authors` VALUES ('361','Della Rowland');
INSERT INTO `authors` VALUES ('362','Arthur William Upfield');
INSERT INTO `authors` VALUES ('363','Sally Mandel');
INSERT INTO `authors` VALUES ('364','Robert B. Parker');
INSERT INTO `authors` VALUES ('365','Tim Farrington');
INSERT INTO `authors` VALUES ('366','Shel Silverstein');
INSERT INTO `authors` VALUES ('367','Dan Brown');
INSERT INTO `authors` VALUES ('368','Robert Penn Warren');
INSERT INTO `authors` VALUES ('369','Richard North Patterson');
INSERT INTO `authors` VALUES ('370','Eleanor Cooney');
INSERT INTO `authors` VALUES ('371','Alice Mcdermott');
INSERT INTO `authors` VALUES ('372','Amy Tan');
INSERT INTO `authors` VALUES ('373','Dana Reeve');
INSERT INTO `authors` VALUES ('374','Isobel Bird');
INSERT INTO `authors` VALUES ('375','Nancy Cobb');
INSERT INTO `authors` VALUES ('376','Alice Walker');
INSERT INTO `authors` VALUES ('377','Roberto Juarroz');
INSERT INTO `authors` VALUES ('378','Bruce Wilkinson');
INSERT INTO `authors` VALUES ('379','Eric Thompson');
INSERT INTO `authors` VALUES ('380','J.R.R. Tolkien');
INSERT INTO `authors` VALUES ('381','Katie Fforde');
INSERT INTO `authors` VALUES ('382','Anne Perry');
INSERT INTO `authors` VALUES ('383','Todd Herzog');
INSERT INTO `authors` VALUES ('384','John Sandford');
INSERT INTO `authors` VALUES ('385','Peter Hoeg');
INSERT INTO `authors` VALUES ('386','Andrew L. Johnson');
INSERT INTO `authors` VALUES ('387','Wayne W. Dyer');
INSERT INTO `authors` VALUES ('388','Robert James Waller');
INSERT INTO `authors` VALUES ('389','Dick Francis');
INSERT INTO `authors` VALUES ('390','Fay Weldon');
INSERT INTO `authors` VALUES ('391','Hubert Selby');
INSERT INTO `authors` VALUES ('392','Tilden H. Edwards');
INSERT INTO `authors` VALUES ('393','Bobbie Kalman');
INSERT INTO `authors` VALUES ('394','Bradley Warshauer');
INSERT INTO `authors` VALUES ('395','Shirlee Busbee');
INSERT INTO `authors` VALUES ('396','Sten Nadolny');
INSERT INTO `authors` VALUES ('397','Carol Matthews');
INSERT INTO `authors` VALUES ('398','Arthur Golden');
INSERT INTO `authors` VALUES ('399','Gary Paulsen');
INSERT INTO `authors` VALUES ('400','Joan Anderson');
INSERT INTO `authors` VALUES ('401','Bobbie Ann Mason');
INSERT INTO `authors` VALUES ('402','Paul Auster');
INSERT INTO `authors` VALUES ('403','Vicen Villatoro');
INSERT INTO `authors` VALUES ('404','Paul Theroux');
INSERT INTO `authors` VALUES ('405','Georgette Heyer');
INSERT INTO `authors` VALUES ('406','Sue Townsend');
INSERT INTO `authors` VALUES ('407','Richard Russo');
INSERT INTO `authors` VALUES ('408','Venise T. Berry');
INSERT INTO `authors` VALUES ('409','Piers Vitebsky');
INSERT INTO `authors` VALUES ('410','Eric Jerome Dickey');
INSERT INTO `authors` VALUES ('411','Vance Havner');
INSERT INTO `authors` VALUES ('412','Jostein Gaarder');
INSERT INTO `authors` VALUES ('413','Manda Scott');
INSERT INTO `authors` VALUES ('414','Sheri S. Tepper');
INSERT INTO `authors` VALUES ('415','Patricia Highsmith');
INSERT INTO `authors` VALUES ('416','Mary Wollstonecraft Shelley');
INSERT INTO `authors` VALUES ('417','Patricia Reilly Giff');
INSERT INTO `authors` VALUES ('418','Shannon Olson');
INSERT INTO `authors` VALUES ('419','Rachel Harris');
INSERT INTO `authors` VALUES ('420','Michael Palmer');
INSERT INTO `authors` VALUES ('421','Richard Peck');
INSERT INTO `authors` VALUES ('422','Ted L. Nancy');
INSERT INTO `authors` VALUES ('423','Jennifer Lauck');
INSERT INTO `authors` VALUES ('424','Barbara Taylor Bradford');
INSERT INTO `authors` VALUES ('425','Don Miguel Ruiz');
INSERT INTO `authors` VALUES ('426','Terry Pratchett');
INSERT INTO `authors` VALUES ('427','Frank M. Robinson');
INSERT INTO `authors` VALUES ('428','Jodi Compton');
INSERT INTO `authors` VALUES ('429','Jo Dereske');
INSERT INTO `authors` VALUES ('430','Martin Buber');
INSERT INTO `authors` VALUES ('431','Dean R. Koontz');
INSERT INTO `authors` VALUES ('432','Charles De Lint');
INSERT INTO `authors` VALUES ('433','Plato');
INSERT INTO `authors` VALUES ('434','Tim Lahaye');
INSERT INTO `authors` VALUES ('435','Tobias Wolff');
INSERT INTO `authors` VALUES ('436','David Brin');
INSERT INTO `authors` VALUES ('437','Rita Chapman Works');
INSERT INTO `authors` VALUES ('438','Muriel Whitaker');
INSERT INTO `authors` VALUES ('439','Roald Dahl');
INSERT INTO `authors` VALUES ('440','Diane Mott Davidson');
INSERT INTO `authors` VALUES ('441','Lawrence J Crabb');
INSERT INTO `authors` VALUES ('442','Rachel Roberts');
INSERT INTO `authors` VALUES ('443','Tony Hillerman');
INSERT INTO `authors` VALUES ('444','Stephen R. Donaldson');
INSERT INTO `authors` VALUES ('445','Robert S. Levinson');
INSERT INTO `authors` VALUES ('446','Yann Martel');
INSERT INTO `authors` VALUES ('447','Richard Paul Evans');
INSERT INTO `authors` VALUES ('448','Ha Jin');
INSERT INTO `authors` VALUES ('449','Adam Lebor');
INSERT INTO `authors` VALUES ('450','Julia Glass');
INSERT INTO `authors` VALUES ('451','Barbara Vine');
INSERT INTO `authors` VALUES ('452','Stel Pavlou');
INSERT INTO `authors` VALUES ('453','Lorraine Anderson');
INSERT INTO `authors` VALUES ('454','Margaret Maron');
INSERT INTO `authors` VALUES ('455','Sidney Sheldon');
INSERT INTO `authors` VALUES ('456','Dan Quayle');
INSERT INTO `authors` VALUES ('457','Oscar Wilde');
INSERT INTO `authors` VALUES ('458','Barbara Ehrenreich');
INSERT INTO `authors` VALUES ('459','V. A Howard');
INSERT INTO `authors` VALUES ('460','Adam Davies');
INSERT INTO `authors` VALUES ('461','Ian Mcewan');
INSERT INTO `authors` VALUES ('462','Horacio Vazquez-Rial');
INSERT INTO `authors` VALUES ('463','Marion Zimmer Bradley');
INSERT INTO `authors` VALUES ('464','E. Lynn Harris');
INSERT INTO `authors` VALUES ('465','Audrey Niffenegger');
INSERT INTO `authors` VALUES ('466','Luis Sep?Lveda');
INSERT INTO `authors` VALUES ('467','Moon Unit Zappa');
INSERT INTO `authors` VALUES ('468','John Varley');
INSERT INTO `authors` VALUES ('469','Judy Blunt');
INSERT INTO `authors` VALUES ('470','Annie Proulx');
INSERT INTO `authors` VALUES ('471','Paula Danziger');
INSERT INTO `authors` VALUES ('472','Tom Clancy');
INSERT INTO `authors` VALUES ('473','Judith Rossner');
INSERT INTO `authors` VALUES ('474','Michael Connelly');
INSERT INTO `authors` VALUES ('475','Jonathan Pearce');
INSERT INTO `authors` VALUES ('476','Barbara Delinsky');
INSERT INTO `authors` VALUES ('477','David Lewis');
INSERT INTO `authors` VALUES ('478','Judith Mcnaught');
INSERT INTO `authors` VALUES ('479','Bernard Cornwell');
INSERT INTO `authors` VALUES ('480','Jen Banbury');
INSERT INTO `authors` VALUES ('481','Jody Seay');
INSERT INTO `authors` VALUES ('482','Laura Zigman');
INSERT INTO `authors` VALUES ('483','Al Franken');
INSERT INTO `authors` VALUES ('484','John Jakes');
INSERT INTO `authors` VALUES ('485','Alice Sebold');
INSERT INTO `authors` VALUES ('486','Elena Ferrante');
INSERT INTO `authors` VALUES ('487','Marc Gascoigne');
INSERT INTO `authors` VALUES ('488','David Sedaris');
INSERT INTO `authors` VALUES ('489','Colleen Mccullough');
INSERT INTO `authors` VALUES ('490','Carolyn See');
INSERT INTO `authors` VALUES ('491','Jonathan Franzen');
INSERT INTO `authors` VALUES ('492','Carolyne Aarsen');
INSERT INTO `authors` VALUES ('493','Robin Cook');
INSERT INTO `authors` VALUES ('494','James Mccourt');
INSERT INTO `authors` VALUES ('495','Marian Babson');
INSERT INTO `authors` VALUES ('496','Christopher Rice');
INSERT INTO `authors` VALUES ('497','John Berendt');
INSERT INTO `authors` VALUES ('498','Sarah Orne Jewett');
INSERT INTO `authors` VALUES ('499','Akiba Rubinstein');
INSERT INTO `authors` VALUES ('500','Max Allan Collins');
INSERT INTO `authors` VALUES ('501','Nancy Garden');
INSERT INTO `authors` VALUES ('502','Loren D. Estleman');
INSERT INTO `authors` VALUES ('503','Mari Sandoz');
INSERT INTO `authors` VALUES ('504','Carol Ryrie Brink');
INSERT INTO `authors` VALUES ('505','James Lee Burke');
INSERT INTO `authors` VALUES ('506','Michael Rips');
INSERT INTO `authors` VALUES ('507','Laura Hillenbrand');
INSERT INTO `authors` VALUES ('508','Charles L. Squire');
INSERT INTO `authors` VALUES ('509','Spencer Johnson');
INSERT INTO `authors` VALUES ('510','Richard Burton');
INSERT INTO `authors` VALUES ('511','Michel Tournier');
INSERT INTO `authors` VALUES ('512','Brian Kaufman');
INSERT INTO `authors` VALUES ('513','Jane Heller');
INSERT INTO `authors` VALUES ('514','David M. Gitlitz');
INSERT INTO `authors` VALUES ('515','Beverly Hastings');
INSERT INTO `authors` VALUES ('516','Ilona Koidahl');
INSERT INTO `authors` VALUES ('517','Kathleen E. Woodiwiss');
INSERT INTO `authors` VALUES ('518','Lisa Scottoline');
INSERT INTO `authors` VALUES ('519','Scott Turow');
INSERT INTO `authors` VALUES ('520','Jane Mccafferty');
INSERT INTO `authors` VALUES ('521','Michael Ondaatje');
INSERT INTO `authors` VALUES ('522','Jane Smiley');
INSERT INTO `authors` VALUES ('523','Robert A Johnson');
INSERT INTO `authors` VALUES ('524','Charlotte Link');
INSERT INTO `authors` VALUES ('525','Collectif');
INSERT INTO `authors` VALUES ('526','Mark Bowden');
INSERT INTO `authors` VALUES ('527','Richard Bruce Wright');
INSERT INTO `authors` VALUES ('528','Gail Carson Levine');
INSERT INTO `authors` VALUES ('529','Roberto Vecchioni');
INSERT INTO `authors` VALUES ('530','Phyllis Reynolds Naylor');
INSERT INTO `authors` VALUES ('531','Natalie Goldberg');
INSERT INTO `authors` VALUES ('532','Paula Polk Lillard');
INSERT INTO `authors` VALUES ('533','Francis Wheen');
INSERT INTO `authors` VALUES ('534','Elizabeth Peters');
INSERT INTO `authors` VALUES ('535','Julia Spencer-Fleming');
INSERT INTO `authors` VALUES ('536','Eugeni Perea Simn');
INSERT INTO `authors` VALUES ('537','Margaret Truman');
INSERT INTO `authors` VALUES ('538','Thomas Cahill');
INSERT INTO `authors` VALUES ('539','David Schickler');
INSERT INTO `authors` VALUES ('540','Michael Moore');
INSERT INTO `authors` VALUES ('541','Richard Zimler');
INSERT INTO `authors` VALUES ('542','Simon Mawer');
INSERT INTO `authors` VALUES ('543','Dean Koontz');
INSERT INTO `authors` VALUES ('544','Simon Schama');
INSERT INTO `authors` VALUES ('545','Harper Lee');
INSERT INTO `authors` VALUES ('546','Henry Miller');
INSERT INTO `authors` VALUES ('547','Elizabeth Gaskell');
INSERT INTO `authors` VALUES ('548','Rebecca Wells');
INSERT INTO `authors` VALUES ('549','Stephen King');
INSERT INTO `authors` VALUES ('550','Linda Howard');
INSERT INTO `authors` VALUES ('551','David Cordingly');
INSERT INTO `authors` VALUES ('552','Elizabeth Benedict');
INSERT INTO `authors` VALUES ('553','Christine Obbo');
INSERT INTO `authors` VALUES ('554','Alan Spence');
INSERT INTO `authors` VALUES ('555','Anne Mccaffrey');
INSERT INTO `authors` VALUES ('556','Rebecca Winters');
INSERT INTO `authors` VALUES ('557','Janet Evanovich');
INSERT INTO `authors` VALUES ('558','Mark Helprin');
INSERT INTO `authors` VALUES ('559','Luanne Rice');
INSERT INTO `authors` VALUES ('560','Rich Shapero');
INSERT INTO `authors` VALUES ('561','Karen Robards');
INSERT INTO `authors` VALUES ('562','Bruce Fries');
INSERT INTO `authors` VALUES ('563','Roy');
INSERT INTO `authors` VALUES ('564','Susan Wiggs');
INSERT INTO `authors` VALUES ('565','Nick Page');
INSERT INTO `authors` VALUES ('566','H. Jackson Brown');
INSERT INTO `authors` VALUES ('567','Margaret Atwood');
INSERT INTO `authors` VALUES ('568','Alan Alexander Milne');
INSERT INTO `authors` VALUES ('569','Helen Myers');
INSERT INTO `authors` VALUES ('570','Sheila Heti');
INSERT INTO `authors` VALUES ('571','Candice F. Ransom');
INSERT INTO `authors` VALUES ('572','Lynn S. Hightower');
INSERT INTO `authors` VALUES ('573','Melody Carlson');
INSERT INTO `authors` VALUES ('574','Stefanie Scott');
INSERT INTO `authors` VALUES ('575','Sandra Brown');
INSERT INTO `authors` VALUES ('576','Paul Reiser');
INSERT INTO `authors` VALUES ('577','Marguerite Henry');
INSERT INTO `authors` VALUES ('578','Ann Patchett');
INSERT INTO `authors` VALUES ('579','Marilyn French');
INSERT INTO `authors` VALUES ('580','Valerie Martin');
INSERT INTO `authors` VALUES ('581','John Milne');
INSERT INTO `authors` VALUES ('582','Tim Gautreaux');
INSERT INTO `authors` VALUES ('583','David Gemmell');
INSERT INTO `authors` VALUES ('584','Sue Monk Kidd');
INSERT INTO `authors` VALUES ('585','Paul Phifer');
INSERT INTO `authors` VALUES ('586','Carrie Bebris');
INSERT INTO `authors` VALUES ('587','Emma Lathen');
INSERT INTO `authors` VALUES ('588','Iain Banks');
INSERT INTO `authors` VALUES ('589','John G. Neihardt');
INSERT INTO `authors` VALUES ('590','Cokie Roberts');
INSERT INTO `authors` VALUES ('591','Kent Haruf');
INSERT INTO `authors` VALUES ('592','Elizabeth Adler');
INSERT INTO `authors` VALUES ('593','Ariella Papa');
INSERT INTO `authors` VALUES ('594','Michael Crichton');
INSERT INTO `authors` VALUES ('595','Mrius Serra');
INSERT INTO `authors` VALUES ('596','Helen Fielding');
INSERT INTO `authors` VALUES ('597','Bernard Werber');
INSERT INTO `authors` VALUES ('598','Ruth Rendell');
INSERT INTO `authors` VALUES ('599','Charles Noland');
INSERT INTO `authors` VALUES ('600','Patricia Daniels Cornwell');
INSERT INTO `authors` VALUES ('601','Warren W. Wiersbe');
INSERT INTO `authors` VALUES ('602','M. Carme Junyent');
INSERT INTO `authors` VALUES ('603','Marvin Miller');
INSERT INTO `authors` VALUES ('604','Nick Hornby');
INSERT INTO `authors` VALUES ('605','Larry Katzenstein');
INSERT INTO `authors` VALUES ('606','Mary Lawson');
INSERT INTO `authors` VALUES ('607','William Carlos Williams');
INSERT INTO `authors` VALUES ('608','Jacqueline L. Tobin');
INSERT INTO `authors` VALUES ('609','Dr Seuss');
INSERT INTO `authors` VALUES ('610','Raymond Chandler');
INSERT INTO `authors` VALUES ('611','Dominick Dunne');
INSERT INTO `authors` VALUES ('612','Nicola Griffith');
INSERT INTO `authors` VALUES ('613','Helene Siegel');
INSERT INTO `authors` VALUES ('614','Robert A. Heinlein');
INSERT INTO `authors` VALUES ('615','Stephanie Maze');
INSERT INTO `authors` VALUES ('616','Ltd');
INSERT INTO `authors` VALUES ('617','A. C. Gordon');
INSERT INTO `authors` VALUES ('618','Gary Zukav');
INSERT INTO `authors` VALUES ('619','Sandra Cisneros');
INSERT INTO `authors` VALUES ('620','C. S. Lewis');
INSERT INTO `authors` VALUES ('621','Robert Hendrickson');
INSERT INTO `authors` VALUES ('622','Celia Brooks Brown');
INSERT INTO `authors` VALUES ('623','Mary Jane Clark');
INSERT INTO `authors` VALUES ('624','Barry Neil Kaufman');
INSERT INTO `authors` VALUES ('625','Walter Wick');
INSERT INTO `authors` VALUES ('626','Joanne Harris');
INSERT INTO `authors` VALUES ('627','Dave Barry');
INSERT INTO `authors` VALUES ('628','Fern Michaels');
INSERT INTO `authors` VALUES ('629','Elizabeth Strout');
INSERT INTO `authors` VALUES ('630','Ted Dekker');
INSERT INTO `authors` VALUES ('631','Glendon Swarthout');
INSERT INTO `authors` VALUES ('632','Robert G. Allen');
INSERT INTO `authors` VALUES ('633','Orson Scott Card');
INSERT INTO `authors` VALUES ('634','Sebastian Junger');
INSERT INTO `authors` VALUES ('635','Wallace Stegner');
INSERT INTO `authors` VALUES ('636','Frederick J. Moody');
INSERT INTO `authors` VALUES ('637','Jaume Cap');
INSERT INTO `authors` VALUES ('638','Pearl Abraham');
INSERT INTO `authors` VALUES ('639','O. Carol Simonton Md');
INSERT INTO `authors` VALUES ('640','Shana Corey');
INSERT INTO `authors` VALUES ('641','Emile Zola');
INSERT INTO `authors` VALUES ('642','Melissa Bank');
INSERT INTO `authors` VALUES ('643','Kirk Kazanjian');
INSERT INTO `authors` VALUES ('644','Alice Hoffman');
INSERT INTO `authors` VALUES ('645','Wolfgang Hohlbein');
INSERT INTO `authors` VALUES ('646','Lynn Coady');
INSERT INTO `authors` VALUES ('647','Jessica Fletcher');
INSERT INTO `authors` VALUES ('648','David Frum');
INSERT INTO `authors` VALUES ('649','Ellen Rimbauer');
INSERT INTO `authors` VALUES ('650','Anne Rice');
INSERT INTO `authors` VALUES ('651','Jeffrey Eugenides');
INSERT INTO `authors` VALUES ('652','Wally Lamb');
INSERT INTO `authors` VALUES ('653','Deborah Mcdowell');
INSERT INTO `authors` VALUES ('654','Franklin W. Dixon');
INSERT INTO `authors` VALUES ('655','Donald F. Kettl');
INSERT INTO `authors` VALUES ('656','Michael Lewis');
INSERT INTO `authors` VALUES ('657','Chuck Hill');
INSERT INTO `authors` VALUES ('658','Neil Gaiman');
INSERT INTO `authors` VALUES ('659','Carl Hausman');
INSERT INTO `authors` VALUES ('660','John Steinbeck');
INSERT INTO `authors` VALUES ('661','Clive Cussler');
INSERT INTO `authors` VALUES ('662','Gwyn Hyman Rubio');
INSERT INTO `authors` VALUES ('663','Renan Demirkan');
INSERT INTO `authors` VALUES ('664','Alisa Kwitney');
INSERT INTO `authors` VALUES ('665','V. S. Naipaul');
INSERT INTO `authors` VALUES ('666','Enid Blyton');
INSERT INTO `authors` VALUES ('667','Vladimir Nabokov');
INSERT INTO `authors` VALUES ('668','Diane Johnson');
INSERT INTO `authors` VALUES ('669','Andrea Kane');
INSERT INTO `authors` VALUES ('670','Isabel Allende');
INSERT INTO `authors` VALUES ('671','Laura Ingall Wilder');
INSERT INTO `authors` VALUES ('672','Ellen Datlow');
INSERT INTO `authors` VALUES ('673','David Morrell');
INSERT INTO `authors` VALUES ('674','Dinah L. Moche');
INSERT INTO `authors` VALUES ('675','Ann-Marie Macdonald');
INSERT INTO `authors` VALUES ('676','Olivia Goldsmith');
INSERT INTO `authors` VALUES ('677','Madelyn Arnold');
INSERT INTO `authors` VALUES ('678','Carlo D\'Este');
INSERT INTO `authors` VALUES ('679','Eileen Goudge');
INSERT INTO `authors` VALUES ('680','Jacqueline Woodson');
INSERT INTO `authors` VALUES ('681','Clifford Stoll');
INSERT INTO `authors` VALUES ('682','Elizabeth Wurtzel');
INSERT INTO `authors` VALUES ('683','Alexandra David-N?El');
INSERT INTO `authors` VALUES ('684','Mary Brave Bird');
INSERT INTO `authors` VALUES ('685','Faye Kellerman');
INSERT INTO `authors` VALUES ('686','Jose Ortega Y Gaset');
INSERT INTO `authors` VALUES ('687','Charles Dickens');
INSERT INTO `authors` VALUES ('688','Susan Conant');
INSERT INTO `authors` VALUES ('689','Dolores Krieger');
INSERT INTO `authors` VALUES ('690','Sandra Dallas');
INSERT INTO `authors` VALUES ('691','Scott Spencer');
INSERT INTO `authors` VALUES ('692','Frank E. Peretti');
INSERT INTO `authors` VALUES ('693','Randy Alcorn');
INSERT INTO `authors` VALUES ('694','Ann Beattie');
INSERT INTO `authors` VALUES ('695','Mike Thaler');
INSERT INTO `authors` VALUES ('696','Christopher Finch');
INSERT INTO `authors` VALUES ('697','Helen Brooks');
INSERT INTO `authors` VALUES ('698','Belva Plain');
INSERT INTO `authors` VALUES ('699','David Guterson');
INSERT INTO `authors` VALUES ('700','Liz Trigg');
INSERT INTO `authors` VALUES ('701','Dorothy Gilman');
INSERT INTO `authors` VALUES ('702','Walter Cronkite');
INSERT INTO `authors` VALUES ('703','Francesca Marciano');
INSERT INTO `authors` VALUES ('704','David Feldman');
INSERT INTO `authors` VALUES ('705','Nathaniel Hawthorne');
INSERT INTO `authors` VALUES ('706','Sharyn Mccrumb');
INSERT INTO `authors` VALUES ('707','Mark Twain');
INSERT INTO `authors` VALUES ('708','Stephen Gazi');
INSERT INTO `authors` VALUES ('709','Carl Sagan');
INSERT INTO `authors` VALUES ('710','Patricia Gaffney');
INSERT INTO `authors` VALUES ('711','Gill Farrer-Halls');
INSERT INTO `authors` VALUES ('712','John Darnton');
INSERT INTO `authors` VALUES ('713','Robynn Clairday');
INSERT INTO `authors` VALUES ('714','Kevin Sullivan');
INSERT INTO `authors` VALUES ('715','Frances Kuffel');
INSERT INTO `authors` VALUES ('716','Lilian Jackson Braun');
INSERT INTO `authors` VALUES ('717','Kathleen Duey');
INSERT INTO `authors` VALUES ('718','Robert Cowley');
INSERT INTO `authors` VALUES ('719','Sarah Waters');
INSERT INTO `authors` VALUES ('720','Jesse S. Ostrow');
INSERT INTO `authors` VALUES ('721','Isabel Wolff');
INSERT INTO `authors` VALUES ('722','E. B. White');
INSERT INTO `authors` VALUES ('723','Joyce Reardon');
INSERT INTO `authors` VALUES ('724','Anthony J Alessandra');
INSERT INTO `authors` VALUES ('725','Margriet De Moor');
INSERT INTO `authors` VALUES ('726','Linda Goodman');
INSERT INTO `authors` VALUES ('727','Edith Wharton');
INSERT INTO `authors` VALUES ('728','Margaret Weis');
INSERT INTO `authors` VALUES ('729','Shirley Rousseau Murphy');
INSERT INTO `authors` VALUES ('730','Carole Nelson Douglas');
INSERT INTO `authors` VALUES ('731','Pergaud');
INSERT INTO `authors` VALUES ('732','P Coelho');
INSERT INTO `authors` VALUES ('733','Arabella Weir');
INSERT INTO `authors` VALUES ('734','Samuel Richardson');
INSERT INTO `authors` VALUES ('735','Paolo Coelho');
INSERT INTO `authors` VALUES ('736','Chaim Potok');
INSERT INTO `authors` VALUES ('737','Diana Gabaldon');
INSERT INTO `authors` VALUES ('738','Allan Zola Kronzek');
INSERT INTO `authors` VALUES ('739','William J. Kennedy');
INSERT INTO `authors` VALUES ('740','Lewis Carroll');
INSERT INTO `authors` VALUES ('741','Carl Hiaasen');
INSERT INTO `authors` VALUES ('742','Hazel Harrison');
INSERT INTO `authors` VALUES ('743','Jack Higgins');
INSERT INTO `authors` VALUES ('744','Stephen Donaldson');
INSERT INTO `authors` VALUES ('745','Danielle Steel');
INSERT INTO `authors` VALUES ('746','Homer Hickam');
INSERT INTO `authors` VALUES ('747','Michael Hudson');
INSERT INTO `authors` VALUES ('748','Erich Maria Remarque');
INSERT INTO `authors` VALUES ('749','Vctor Mora');
INSERT INTO `authors` VALUES ('750','Irene Gonzalez Frei');
INSERT INTO `authors` VALUES ('751','Antonio Albanese');
INSERT INTO `authors` VALUES ('752','Thomas Harris');
INSERT INTO `authors` VALUES ('753','Richard Brassey');
INSERT INTO `authors` VALUES ('754','Jane Hamilton');
INSERT INTO `authors` VALUES ('755','Barbara Kingsolver');
INSERT INTO `authors` VALUES ('756','Nora Roberts');
INSERT INTO `authors` VALUES ('757','Judy Hamilton');
INSERT INTO `authors` VALUES ('758','Joan Agut');
INSERT INTO `authors` VALUES ('759','Meg Cabot');
INSERT INTO `authors` VALUES ('760','Cyrano De Bergerac');
INSERT INTO `authors` VALUES ('761','Paul Hattaway');
INSERT INTO `authors` VALUES ('762','Bill Bradley');
INSERT INTO `authors` VALUES ('763','Toni Morrison');
INSERT INTO `authors` VALUES ('764','Howard Fast');
INSERT INTO `authors` VALUES ('765','L.M. Montgomery');
INSERT INTO `authors` VALUES ('766','Thomas Hardy');
INSERT INTO `authors` VALUES ('767','William Goldman');
INSERT INTO `authors` VALUES ('768','James C. Robertson');
INSERT INTO `authors` VALUES ('769','Adeline Yen Mah');
INSERT INTO `authors` VALUES ('770','Warren  Bennis');
INSERT INTO `authors` VALUES ('771','Martha Grimes');
INSERT INTO `authors` VALUES ('772','Billie Livingston');
INSERT INTO `authors` VALUES ('773','Christa Wichterich');
INSERT INTO `authors` VALUES ('774','Lee Smith');
INSERT INTO `authors` VALUES ('775','Louisa May Alcott');
INSERT INTO `authors` VALUES ('776','Lisa Gardner');
INSERT INTO `authors` VALUES ('777','Russell Banks');
INSERT INTO `authors` VALUES ('778','Stewart O\'Nan');
INSERT INTO `authors` VALUES ('779','Louis L\'Amour');
INSERT INTO `authors` VALUES ('780','Langston Hughes');
INSERT INTO `authors` VALUES ('781','Sara Orwig');
INSERT INTO `authors` VALUES ('782','Bob Thiele');
INSERT INTO `authors` VALUES ('783','Raymond Radiguet');
INSERT INTO `authors` VALUES ('784','John Irving');
INSERT INTO `authors` VALUES ('785','Stanley Morison');
INSERT INTO `authors` VALUES ('786','Paul Woodruff');
INSERT INTO `authors` VALUES ('787','Joe Keenan');
