INSERT INTO `publishers` VALUES ('0','Heyne');
INSERT INTO `publishers` VALUES ('1','Crimeline');
INSERT INTO `publishers` VALUES ('2','Buy Books On The Web.Com');
INSERT INTO `publishers` VALUES ('3','Pan Macmillan');
INSERT INTO `publishers` VALUES ('4','Alfred A. Knopf');
INSERT INTO `publishers` VALUES ('5','Miramax');
INSERT INTO `publishers` VALUES ('6','Red Dress Ink');
INSERT INTO `publishers` VALUES ('7','Health Communications');
INSERT INTO `publishers` VALUES ('8','St. Martin\'S Press');
INSERT INTO `publishers` VALUES ('9','Bantam Books');
INSERT INTO `publishers` VALUES ('10','Livre De Poche French');
INSERT INTO `publishers` VALUES ('11','Hyperion Books For Children');
INSERT INTO `publishers` VALUES ('12','Goldmann');
INSERT INTO `publishers` VALUES ('13','Castle Books');
INSERT INTO `publishers` VALUES ('14','Edicions De La Magrana');
INSERT INTO `publishers` VALUES ('15','Harvest Books');
INSERT INTO `publishers` VALUES ('16','Pages Publishing Group');
INSERT INTO `publishers` VALUES ('17','Trafalgar Square');
INSERT INTO `publishers` VALUES ('18','St. Martin\'S Griffin');
INSERT INTO `publishers` VALUES ('19','Faber Children\'S Books');
INSERT INTO `publishers` VALUES ('20','Dial Books');
INSERT INTO `publishers` VALUES ('21','Edicions 62');
INSERT INTO `publishers` VALUES ('22','Soho Press');
INSERT INTO `publishers` VALUES ('23','Ferguson Publishing Company');
INSERT INTO `publishers` VALUES ('24','Nan A. Talese');
INSERT INTO `publishers` VALUES ('25','Golden Books Publishing Company');
INSERT INTO `publishers` VALUES ('26','Pocket Star');
INSERT INTO `publishers` VALUES ('27','Arcadia Books');
INSERT INTO `publishers` VALUES ('28','Bantam Dell Pub Group');
INSERT INTO `publishers` VALUES ('29','Random House Inc');
INSERT INTO `publishers` VALUES ('30','Diogenes Verlag');
INSERT INTO `publishers` VALUES ('31','Gulf Publishing Company');
INSERT INTO `publishers` VALUES ('32','Editech Pr');
INSERT INTO `publishers` VALUES ('33','Aufbau Tb');
INSERT INTO `publishers` VALUES ('34','Mysterious Press');
INSERT INTO `publishers` VALUES ('35','Avon Trade');
INSERT INTO `publishers` VALUES ('36','Fawcett');
INSERT INTO `publishers` VALUES ('37','Thomas Nelson');
INSERT INTO `publishers` VALUES ('38','Sunflower Press');
INSERT INTO `publishers` VALUES ('39','University Of California Press');
INSERT INTO `publishers` VALUES ('40','Penguin Books Ltd');
INSERT INTO `publishers` VALUES ('41','Akashic Books');
INSERT INTO `publishers` VALUES ('42','Minotauro');
INSERT INTO `publishers` VALUES ('43','Aladdin');
INSERT INTO `publishers` VALUES ('44','Canongate Books Ltd');
INSERT INTO `publishers` VALUES ('45','Laurel Leaf');
INSERT INTO `publishers` VALUES ('46','Love Spell');
INSERT INTO `publishers` VALUES ('47','Reader\'S Digest');
INSERT INTO `publishers` VALUES ('48','Scholastic Inc');
INSERT INTO `publishers` VALUES ('49','Kiepenheuer &Amp; Witsch');
INSERT INTO `publishers` VALUES ('50','Jossey-Bass');
INSERT INTO `publishers` VALUES ('51','Pocket Books');
INSERT INTO `publishers` VALUES ('52','Plaza &Amp; Jans');
INSERT INTO `publishers` VALUES ('53','Bantam Doubleday Dell');
INSERT INTO `publishers` VALUES ('54','1Stbooks Library');
INSERT INTO `publishers` VALUES ('55','University Of Nebraska Press');
INSERT INTO `publishers` VALUES ('56','Infinity Publishing (Pa)');
INSERT INTO `publishers` VALUES ('57','Harperentertainment');
INSERT INTO `publishers` VALUES ('58','Watson-Guptill Publications');
INSERT INTO `publishers` VALUES ('59','Vintage');
INSERT INTO `publishers` VALUES ('60','Inner Ocean Publishing');
INSERT INTO `publishers` VALUES ('61','Pearson Education');
INSERT INTO `publishers` VALUES ('62','National Geographic Society');
INSERT INTO `publishers` VALUES ('63','L?Bbe');
INSERT INTO `publishers` VALUES ('64','Wings');
INSERT INTO `publishers` VALUES ('65','Destino');
INSERT INTO `publishers` VALUES ('66','Harmony');
INSERT INTO `publishers` VALUES ('67','Zebra Books');
INSERT INTO `publishers` VALUES ('68','Random House Trade Paperbacks');
INSERT INTO `publishers` VALUES ('69','Farrar Straus &Amp; Giroux');
INSERT INTO `publishers` VALUES ('70','Harcourt');
INSERT INTO `publishers` VALUES ('71','Warner Books (Mm)');
INSERT INTO `publishers` VALUES ('72','Readers Digest');
INSERT INTO `publishers` VALUES ('73','Livre De Poche');
INSERT INTO `publishers` VALUES ('74','Quill (Harpercollins)');
INSERT INTO `publishers` VALUES ('75','Columna');
INSERT INTO `publishers` VALUES ('76','Delta Systems');
INSERT INTO `publishers` VALUES ('77','Mira Books');
INSERT INTO `publishers` VALUES ('78','Natl Book Network');
INSERT INTO `publishers` VALUES ('79','Harper Mass Market Paperbacks (Mm)');
INSERT INTO `publishers` VALUES ('80','New Amer Library');
INSERT INTO `publishers` VALUES ('81','Putnam Pub Group');
INSERT INTO `publishers` VALUES ('82','Editorial Empries');
INSERT INTO `publishers` VALUES ('83','Cypress House');
INSERT INTO `publishers` VALUES ('84','Press Gang Publishers');
INSERT INTO `publishers` VALUES ('85','Michael Joseph Ltd');
INSERT INTO `publishers` VALUES ('86','Alpha Books');
INSERT INTO `publishers` VALUES ('87','Jove Books');
INSERT INTO `publishers` VALUES ('88','Regan Books');
INSERT INTO `publishers` VALUES ('89','Fabbri - Rcs Libri');
INSERT INTO `publishers` VALUES ('90','Westbow Press');
INSERT INTO `publishers` VALUES ('91','Harpercollins Publishers');
INSERT INTO `publishers` VALUES ('92','Doubleday');
INSERT INTO `publishers` VALUES ('93','Tyndale House Publishers');
INSERT INTO `publishers` VALUES ('94','Piper');
INSERT INTO `publishers` VALUES ('95','Picador (Uk)');
INSERT INTO `publishers` VALUES ('96','Putnam Publishing Group');
INSERT INTO `publishers` VALUES ('97','Playmore Inc. Publishers');
INSERT INTO `publishers` VALUES ('98','Deutscher Taschenbuch Verlag (Dtv)');
INSERT INTO `publishers` VALUES ('99','Celestial Arts');
INSERT INTO `publishers` VALUES ('100','House Of Anansi Press');
INSERT INTO `publishers` VALUES ('101','Jump At The Sun');
INSERT INTO `publishers` VALUES ('102','Southwater Publishing');
INSERT INTO `publishers` VALUES ('103','Noble House');
INSERT INTO `publishers` VALUES ('104','Scholastic Paperbacks');
INSERT INTO `publishers` VALUES ('105','Main Street Books');
INSERT INTO `publishers` VALUES ('106','Mira');
INSERT INTO `publishers` VALUES ('107','Word Publishing');
INSERT INTO `publishers` VALUES ('108','Navpress');
INSERT INTO `publishers` VALUES ('109','Plume Books');
INSERT INTO `publishers` VALUES ('110','Infinity Publishing.Com');
INSERT INTO `publishers` VALUES ('111','O. W. Barth Bei Scherz');
INSERT INTO `publishers` VALUES ('112','Troll Communications Llc');
INSERT INTO `publishers` VALUES ('113','W. W. Norton &Amp; Company');
INSERT INTO `publishers` VALUES ('114','Dover Publications');
INSERT INTO `publishers` VALUES ('115','Hal Leonard Corp');
INSERT INTO `publishers` VALUES ('116','Dell');
INSERT INTO `publishers` VALUES ('117','Hanser');
INSERT INTO `publishers` VALUES ('118','Ivy Books');
INSERT INTO `publishers` VALUES ('119','Llewellyn Publications');
INSERT INTO `publishers` VALUES ('120','Touchstone');
INSERT INTO `publishers` VALUES ('121','Ohio University Press');
INSERT INTO `publishers` VALUES ('122','Editorial Laia');
INSERT INTO `publishers` VALUES ('123','Beacon Press');
INSERT INTO `publishers` VALUES ('124','Shambhala');
INSERT INTO `publishers` VALUES ('125','Penguin Books');
INSERT INTO `publishers` VALUES ('126','Access Press (Harpercollins)');
INSERT INTO `publishers` VALUES ('127','Forge Books');
INSERT INTO `publishers` VALUES ('128','Brilliance Audio - Trade');
INSERT INTO `publishers` VALUES ('129','Bantam Classics');
INSERT INTO `publishers` VALUES ('130','Deutscher Taschenbuch Verlag');
INSERT INTO `publishers` VALUES ('131','Tor Fantasy');
INSERT INTO `publishers` VALUES ('132','Random House Canada');
INSERT INTO `publishers` VALUES ('133','River City Pub');
INSERT INTO `publishers` VALUES ('134','Harperperennial');
INSERT INTO `publishers` VALUES ('135','Harpertrophy');
INSERT INTO `publishers` VALUES ('136','Salamandra');
INSERT INTO `publishers` VALUES ('137','Ballantine Books');
INSERT INTO `publishers` VALUES ('138','Onyx Books');
INSERT INTO `publishers` VALUES ('139','Area');
INSERT INTO `publishers` VALUES ('140','Dtv');
INSERT INTO `publishers` VALUES ('141','Andrew Scott Publishers');
INSERT INTO `publishers` VALUES ('142','Girl Press');
INSERT INTO `publishers` VALUES ('143','Phoenix Books');
INSERT INTO `publishers` VALUES ('144','Union Gnrale D\'Ditions');
INSERT INTO `publishers` VALUES ('145','Avon Books');
INSERT INTO `publishers` VALUES ('146','Fawcett Books');
INSERT INTO `publishers` VALUES ('147','Citadel Press');
INSERT INTO `publishers` VALUES ('148','Random House Value Publishing');
INSERT INTO `publishers` VALUES ('149','Modern Library');
INSERT INTO `publishers` VALUES ('150','Houghton Mifflin Company');
INSERT INTO `publishers` VALUES ('151','Windstorm Creative');
INSERT INTO `publishers` VALUES ('152','W W Norton &Amp; Co Inc');
INSERT INTO `publishers` VALUES ('153','The Lyons Press');
INSERT INTO `publishers` VALUES ('154','Laia');
INSERT INTO `publishers` VALUES ('155','Black Sparrow Books');
INSERT INTO `publishers` VALUES ('156','Penguin Putnam~Mass');
INSERT INTO `publishers` VALUES ('157','Artisan Publishers');
INSERT INTO `publishers` VALUES ('158','Putnam Pub Group (Paper)');
INSERT INTO `publishers` VALUES ('159','New York Review Of Books');
INSERT INTO `publishers` VALUES ('160','Warner Books');
INSERT INTO `publishers` VALUES ('161','Ryland Peters &Amp; Small Ltd');
INSERT INTO `publishers` VALUES ('162','Little Brown &Amp; Co');
INSERT INTO `publishers` VALUES ('163','Flammarion');
INSERT INTO `publishers` VALUES ('164','Harlequin');
INSERT INTO `publishers` VALUES ('165','Hodder &Amp; Stoughton General Division');
INSERT INTO `publishers` VALUES ('166','Palgrave-Macmillan');
INSERT INTO `publishers` VALUES ('167','Mariner Books');
INSERT INTO `publishers` VALUES ('168','Reston Pub. Co');
INSERT INTO `publishers` VALUES ('169','Farrar Straus Giroux');
INSERT INTO `publishers` VALUES ('170','Amber-Allen Publishing');
INSERT INTO `publishers` VALUES ('171','Ecco Press');
INSERT INTO `publishers` VALUES ('172','St. Martin\'S Minotaur');
INSERT INTO `publishers` VALUES ('173','Hill &Amp; Wang');
INSERT INTO `publishers` VALUES ('174','Penguin Usa');
INSERT INTO `publishers` VALUES ('175','Routledge');
INSERT INTO `publishers` VALUES ('176','Lgf');
INSERT INTO `publishers` VALUES ('177','Pantheon');
INSERT INTO `publishers` VALUES ('178','Anchor');
INSERT INTO `publishers` VALUES ('179','G. P. Putnam\'S Sons');
INSERT INTO `publishers` VALUES ('180','Ediciones Temas De Hoy');
INSERT INTO `publishers` VALUES ('181','Warner Vision');
INSERT INTO `publishers` VALUES ('182','Riverhead Books');
INSERT INTO `publishers` VALUES ('183','Pub Group West');
INSERT INTO `publishers` VALUES ('184','Brockhampton Press');
INSERT INTO `publishers` VALUES ('185','Einaudi');
INSERT INTO `publishers` VALUES ('186','Henry Holt &Amp; Company');
INSERT INTO `publishers` VALUES ('187','Doubleday Books');
INSERT INTO `publishers` VALUES ('188','Harpercollins Publisher');
INSERT INTO `publishers` VALUES ('189','Price Stern Sloan');
INSERT INTO `publishers` VALUES ('190','Yearling Books');
INSERT INTO `publishers` VALUES ('191','Amereon Limited');
INSERT INTO `publishers` VALUES ('192','Little Brown &Amp; Company');
INSERT INTO `publishers` VALUES ('193','Perennial');
INSERT INTO `publishers` VALUES ('194','Edizioni E/O');
INSERT INTO `publishers` VALUES ('195','Golden Books');
INSERT INTO `publishers` VALUES ('196','Bantam Dell Publishing Group');
INSERT INTO `publishers` VALUES ('197','Harperfestival');
INSERT INTO `publishers` VALUES ('198','Four Walls Eight Windows');
INSERT INTO `publishers` VALUES ('199','Baldini&Amp;Castoldi');
INSERT INTO `publishers` VALUES ('200','W Publishing Group');
INSERT INTO `publishers` VALUES ('201','Harpercollins Juvenile Books');
INSERT INTO `publishers` VALUES ('202','St. Martin\'S Paperbacks');
INSERT INTO `publishers` VALUES ('203','Random House Children\'S Books');
INSERT INTO `publishers` VALUES ('204','Harpercollins Library');
INSERT INTO `publishers` VALUES ('205','Mcclelland &Amp; Stewart');
INSERT INTO `publishers` VALUES ('206','Candlewick Press (Ma)');
INSERT INTO `publishers` VALUES ('207','Simon &Amp; Schuster (Trade Division)');
INSERT INTO `publishers` VALUES ('208','Downtown Book Center');
INSERT INTO `publishers` VALUES ('209','Picador');
INSERT INTO `publishers` VALUES ('210','Penguin Usa (Paper)');
INSERT INTO `publishers` VALUES ('211','Atria');
INSERT INTO `publishers` VALUES ('212','Star Trek');
INSERT INTO `publishers` VALUES ('213','Epicenter Press');
INSERT INTO `publishers` VALUES ('214','Faber Faber Inc');
INSERT INTO `publishers` VALUES ('215','Orb Books');
INSERT INTO `publishers` VALUES ('216','Schocken Books');
INSERT INTO `publishers` VALUES ('217','Viking Children\'S Books');
INSERT INTO `publishers` VALUES ('218','Random House Childrens Books');
INSERT INTO `publishers` VALUES ('219','Random House Books For Young Readers');
INSERT INTO `publishers` VALUES ('220','Broadway');
INSERT INTO `publishers` VALUES ('221','Del Rey');
INSERT INTO `publishers` VALUES ('222','Barnes Noble Books');
INSERT INTO `publishers` VALUES ('223','Point Fantasy');
INSERT INTO `publishers` VALUES ('224','Scribner Paper Fiction');
INSERT INTO `publishers` VALUES ('225','Alyson Books');
INSERT INTO `publishers` VALUES ('226','Thorndike Pr');
INSERT INTO `publishers` VALUES ('227','Thomas Dunne Books');
INSERT INTO `publishers` VALUES ('228','Wizards Of The Coast');
INSERT INTO `publishers` VALUES ('229','Harry N Abrams');
INSERT INTO `publishers` VALUES ('230','Distribooks Inc');
INSERT INTO `publishers` VALUES ('231','Monarch Books');
INSERT INTO `publishers` VALUES ('232','Ntc/Contemporary Publishing Company');
INSERT INTO `publishers` VALUES ('233','Pantheon Books');
INSERT INTO `publishers` VALUES ('234','Harper Collins - Uk');
INSERT INTO `publishers` VALUES ('235','St Martins Pr');
INSERT INTO `publishers` VALUES ('236','Alyson Publications');
INSERT INTO `publishers` VALUES ('237','Puffin Books');
INSERT INTO `publishers` VALUES ('238','Grove Press');
INSERT INTO `publishers` VALUES ('239','Macadam/Cage Publishing');
INSERT INTO `publishers` VALUES ('240','Tor Books (Mm)');
INSERT INTO `publishers` VALUES ('241','Dell Publishing Company');
INSERT INTO `publishers` VALUES ('242','Plume');
INSERT INTO `publishers` VALUES ('243','F.J. Moody');
INSERT INTO `publishers` VALUES ('244','Rising Tide Press (Az)');
INSERT INTO `publishers` VALUES ('245','Pinnacle Books');
INSERT INTO `publishers` VALUES ('246','Last Knight Pub Co');
INSERT INTO `publishers` VALUES ('247','Saunders College Publishing');
INSERT INTO `publishers` VALUES ('248','Puffin');
INSERT INTO `publishers` VALUES ('249','Washington Square Press');
INSERT INTO `publishers` VALUES ('250','Harpersanfrancisco');
INSERT INTO `publishers` VALUES ('251','David R. Godine Publisher');
INSERT INTO `publishers` VALUES ('252','Manning Publications');
INSERT INTO `publishers` VALUES ('253','Abacus');
INSERT INTO `publishers` VALUES ('254','W.W. Norton &Amp; Company');
INSERT INTO `publishers` VALUES ('255','Mcgraw-Hill');
INSERT INTO `publishers` VALUES ('256','Diogenes');
INSERT INTO `publishers` VALUES ('257','Diamond Books (Ny)');
INSERT INTO `publishers` VALUES ('258','Sagebrush Bound');
INSERT INTO `publishers` VALUES ('259','Readers Digest Assn');
INSERT INTO `publishers` VALUES ('260','Btb');
INSERT INTO `publishers` VALUES ('261','Harpercollins');
INSERT INTO `publishers` VALUES ('262','Kensington Publishing Corp.');
INSERT INTO `publishers` VALUES ('263','Little Brown And Company');
INSERT INTO `publishers` VALUES ('264','Tor Books');
INSERT INTO `publishers` VALUES ('265','Picador Usa');
INSERT INTO `publishers` VALUES ('266','F. H. Revell');
INSERT INTO `publishers` VALUES ('267','Pocket');
INSERT INTO `publishers` VALUES ('268','Michael O\'Mara Books');
INSERT INTO `publishers` VALUES ('269','Gallimard');
INSERT INTO `publishers` VALUES ('270','Griffin Trade Paperback');
INSERT INTO `publishers` VALUES ('271','Multnomah');
INSERT INTO `publishers` VALUES ('272','Tusquets');
INSERT INTO `publishers` VALUES ('273','Baker Book House');
INSERT INTO `publishers` VALUES ('274','Teamcom Books');
INSERT INTO `publishers` VALUES ('275','Hackett Publishing Company');
INSERT INTO `publishers` VALUES ('276','Distribooks');
INSERT INTO `publishers` VALUES ('277','Too Far');
INSERT INTO `publishers` VALUES ('278','I Books');
INSERT INTO `publishers` VALUES ('279','Free Press');
INSERT INTO `publishers` VALUES ('280','Harperflamingo Canada');
INSERT INTO `publishers` VALUES ('281','Atheneum');
INSERT INTO `publishers` VALUES ('282','W. Morrow');
INSERT INTO `publishers` VALUES ('283','Landoll');
INSERT INTO `publishers` VALUES ('284','Hackett Pub Co Inc');
INSERT INTO `publishers` VALUES ('285','Everyman\'S Library');
INSERT INTO `publishers` VALUES ('286','Eos');
INSERT INTO `publishers` VALUES ('287','Egmont Childrens Books');
INSERT INTO `publishers` VALUES ('288','Del Rey Books');
INSERT INTO `publishers` VALUES ('289','Stonewall Inn Editions');
INSERT INTO `publishers` VALUES ('290','Scholastic');
INSERT INTO `publishers` VALUES ('291','Arcade Publishing');
INSERT INTO `publishers` VALUES ('292','Lectorum Pubns (J)');
INSERT INTO `publishers` VALUES ('293','Signet Book');
INSERT INTO `publishers` VALUES ('294','Spectra');
INSERT INTO `publishers` VALUES ('295','Lomond Books');
INSERT INTO `publishers` VALUES ('296','Childrens Press');
INSERT INTO `publishers` VALUES ('297','Delacorte Books For Young Readers');
INSERT INTO `publishers` VALUES ('298','Winedale Publishing');
INSERT INTO `publishers` VALUES ('299','Morehouse Group');
INSERT INTO `publishers` VALUES ('300','Vintage Books Usa');
INSERT INTO `publishers` VALUES ('301','Spectra Books');
INSERT INTO `publishers` VALUES ('302','Mtv');
INSERT INTO `publishers` VALUES ('303','Villard Books');
INSERT INTO `publishers` VALUES ('304','Back Bay Books');
INSERT INTO `publishers` VALUES ('305','Kidsbooks.Com');
INSERT INTO `publishers` VALUES ('306','Harper Mass Market Paperbacks');
INSERT INTO `publishers` VALUES ('307','Harpertorch');
INSERT INTO `publishers` VALUES ('308','Trafalgar Square Books');
INSERT INTO `publishers` VALUES ('309','Andrews Mcmeel Publishing');
INSERT INTO `publishers` VALUES ('310','Dutton Books');
INSERT INTO `publishers` VALUES ('311','New English Library');
INSERT INTO `publishers` VALUES ('312','Chambers Harrap Publishers Ltd');
INSERT INTO `publishers` VALUES ('313','Regal Books');
INSERT INTO `publishers` VALUES ('314','Ywam Publishing');
INSERT INTO `publishers` VALUES ('315','Ullstein Tb');
INSERT INTO `publishers` VALUES ('316','Silhouette');
INSERT INTO `publishers` VALUES ('317','Crabtree Publishing Company');
INSERT INTO `publishers` VALUES ('318','Adams Media Corp');
INSERT INTO `publishers` VALUES ('319','Bloomsbury Publishing Plc');
INSERT INTO `publishers` VALUES ('320','Houghton Mifflin Co');
INSERT INTO `publishers` VALUES ('321','William Morrow');
INSERT INTO `publishers` VALUES ('322','John Wiley &Amp; Sons Inc');
INSERT INTO `publishers` VALUES ('323','Random House');
INSERT INTO `publishers` VALUES ('324','Ace Books');
INSERT INTO `publishers` VALUES ('325','Push');
INSERT INTO `publishers` VALUES ('326','Chatto &Amp; Windus');
INSERT INTO `publishers` VALUES ('327','Douglas Gibson Books');
INSERT INTO `publishers` VALUES ('328','Sourcebooks Landmark');
INSERT INTO `publishers` VALUES ('329','Fireside');
INSERT INTO `publishers` VALUES ('330','Scribner');
INSERT INTO `publishers` VALUES ('331','Yearling');
INSERT INTO `publishers` VALUES ('332','Dark Horse Comics');
INSERT INTO `publishers` VALUES ('333','Viking Books');
INSERT INTO `publishers` VALUES ('334','Harperprism');
INSERT INTO `publishers` VALUES ('335','J\'Ai Lu');
INSERT INTO `publishers` VALUES ('336','Roc');
INSERT INTO `publishers` VALUES ('337','Broadway Books');
INSERT INTO `publishers` VALUES ('338','Bloomsbury Pub Ltd');
INSERT INTO `publishers` VALUES ('339','Macmillan Publishing Company.');
INSERT INTO `publishers` VALUES ('340','Gallimard French');
INSERT INTO `publishers` VALUES ('341','Signet Classics');
INSERT INTO `publishers` VALUES ('342','Edicoes Asa');
INSERT INTO `publishers` VALUES ('343','Dearborn Financial Publishing');
INSERT INTO `publishers` VALUES ('344','Crown');
INSERT INTO `publishers` VALUES ('345','Hyperion');
INSERT INTO `publishers` VALUES ('346','Wendy Lamb Books');
INSERT INTO `publishers` VALUES ('347','Laure Leaf');
INSERT INTO `publishers` VALUES ('348','Anagrama');
INSERT INTO `publishers` VALUES ('349','Del Sol Press');
INSERT INTO `publishers` VALUES ('350','Atlantic Monthly Press');
INSERT INTO `publishers` VALUES ('351','Ediciones B');
INSERT INTO `publishers` VALUES ('352','Anchor Pub');
INSERT INTO `publishers` VALUES ('353','Image');
INSERT INTO `publishers` VALUES ('354','Owl Books');
INSERT INTO `publishers` VALUES ('355','Authorsomniscient Publishers');
INSERT INTO `publishers` VALUES ('356','Viking Juvenile');
INSERT INTO `publishers` VALUES ('357','Oxford University Press');
INSERT INTO `publishers` VALUES ('358','Steeple Hill');
INSERT INTO `publishers` VALUES ('359','Simon &Amp; Schuster');
INSERT INTO `publishers` VALUES ('360','Penguin Putnam~Trade');
INSERT INTO `publishers` VALUES ('361','Bantam');
INSERT INTO `publishers` VALUES ('362','Quest Books');
INSERT INTO `publishers` VALUES ('363','Starfire');
INSERT INTO `publishers` VALUES ('364','Pleasant Company Publications');
INSERT INTO `publishers` VALUES ('365','Rowohlt Tb.');
INSERT INTO `publishers` VALUES ('366','University Press Of America');
INSERT INTO `publishers` VALUES ('367','Speed Graphics');
INSERT INTO `publishers` VALUES ('368','Rowohlt');
INSERT INTO `publishers` VALUES ('369','Delta');
INSERT INTO `publishers` VALUES ('370','Simon Schuster Trade');
INSERT INTO `publishers` VALUES ('371','Delacorte Press');
INSERT INTO `publishers` VALUES ('372','Emblem Editions');
INSERT INTO `publishers` VALUES ('373','Prentice Hall (K-12)');
INSERT INTO `publishers` VALUES ('374','Firebrand Books');
INSERT INTO `publishers` VALUES ('375','Berkley Publishing Group');
INSERT INTO `publishers` VALUES ('376','Island');
INSERT INTO `publishers` VALUES ('377','Seuil');
INSERT INTO `publishers` VALUES ('378','Avon');
INSERT INTO `publishers` VALUES ('379','Three Rivers Press');
INSERT INTO `publishers` VALUES ('380','W W Norton &Amp; Co');
INSERT INTO `publishers` VALUES ('381','New Directions Publishing Corporation');
INSERT INTO `publishers` VALUES ('382','White Pine Press (Ny)');
INSERT INTO `publishers` VALUES ('383','Signet');
INSERT INTO `publishers` VALUES ('384','Dreamhaven Books');
INSERT INTO `publishers` VALUES ('385','Presses Pocket French');
INSERT INTO `publishers` VALUES ('386','Alianza');
INSERT INTO `publishers` VALUES ('387','Hyperion Press');
INSERT INTO `publishers` VALUES ('388','Lamuv');
INSERT INTO `publishers` VALUES ('389','Magic Carpet Books');
INSERT INTO `publishers` VALUES ('390','Knopf Books For Young Readers');
INSERT INTO `publishers` VALUES ('391','Atria Books');
INSERT INTO `publishers` VALUES ('392','Scholastic Paperbacks (Mm)');
INSERT INTO `publishers` VALUES ('393','Laurel-Leaf Books');
INSERT INTO `publishers` VALUES ('394','Audioworks');
INSERT INTO `publishers` VALUES ('395','Taschen Verlag');
INSERT INTO `publishers` VALUES ('396','Knopf');
